In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/chem/SSC_Chemistry_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/phy/SSC_Physics_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/Bio/SSC_Biology_Datasets.jsonl

In [2]:
from pathlib import Path

jsonl_files = list(Path("/kaggle/input").rglob("*.jsonl"))

for file in jsonl_files:
    print(file)

/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/chem/SSC_Chemistry_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/phy/SSC_Physics_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/Bio/SSC_Biology_Datasets.jsonl

In [3]:
print("Number of JSONL files:", len(jsonl_files))

Number of JSONL files: 3

In [4]:
first_file = jsonl_files[0]

with open(first_file, "r", encoding="utf-8") as file:
    first_line = file.readline()

print(first_line)

{"Question": "রসায়ন কী?", "Hints": ["এটি বিজ্ঞানের একটি শাখা।", "পদার্থের গঠন একটি আলোচনা।", "এতে পদার্থের ধর্ম ও পরিবর্তন মূল বিষয়।", "এর ইংরেজি প্রতিশব্দ 'Chemistry'।", "এটি 'Chemi' শব্দ থেকে এসেছে।"], "ExactAnswer": ["বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদার্থের পরিবর্তন নিয়ে আলোচনা করা হয়।"], "Candidates_Answers": ["বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদার্থের পরিবর্তন নিয়ে আলোচনা করা হয়।", "জীব ও পরিবেশ নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।", "মহাকাশ ও গ্রহ-নক্ষত্র নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।", "পদার্থের গতি ও বল নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।"], "Convergence": [{"Up to 1": 0.5, "Up to 2": 0.65, "Up to 3": 0.8, "Up to 4": 0.95, "Up to 5": 1.0}], "Convergence_Ranked": ["এটি বিজ্ঞানের একটি শাখা।", "পদার্থের গঠন একটি আলোচনা।", "এতে পদার্থের ধর্ম ও পরিবর্তন মূল বিষয়।", "এর ইংরেজি প্রতিশব্দ 'Chemistry'।"], "TopicTags": ["Chemistry", "Definition of Chemistry"]}

In [5]:
import json

record = json.loads(first_line)

print(record)

{'Question': 'রসায়ন কী?', 'Hints': ['এটি বিজ্ঞানের একটি শাখা।', 'পদার্থের গঠন একটি আলোচনা।', 'এতে পদার্থের ধর্ম ও পরিবর্তন মূল বিষয়।', "এর ইংরেজি প্রতিশব্দ 'Chemistry'।", "এটি 'Chemi' শব্দ থেকে এসেছে।"], 'ExactAnswer': ['বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদার্থের পরিবর্তন নিয়ে আলোচনা করা হয়।'], 'Candidates_Answers': ['বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদার্থের পরিবর্তন নিয়ে আলোচনা করা হয়।', 'জীব ও পরিবেশ নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।', 'মহাকাশ ও গ্রহ-নক্ষত্র নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।', 'পদার্থের গতি ও বল নিয়ে আলোচনা করে বিজ্ঞানের যে শাখা।'], 'Convergence': [{'Up to 1': 0.5, 'Up to 2': 0.65, 'Up to 3': 0.8, 'Up to 4': 0.95, 'Up to 5': 1.0}], 'Convergence_Ranked': ['এটি বিজ্ঞানের একটি শাখা।', 'পদার্থের গঠন একটি আলোচনা।', 'এতে পদার্থের ধর্ম ও পরিবর্তন মূল বিষয়।', "এর ইংরেজি প্রতিশব্দ 'Chemistry'।"], 'TopicTags': ['Chemistry', 'Definition of Chemistry']}

In [6]:
print(record["Question"])

রসায়ন কী?

In [7]:
print(record["Hints"])

['এটি বিজ্ঞানের একটি শাখা।', 'পদার্থের গঠন একটি আলোচনা।', 'এতে পদার্থের ধর্ম ও পরিবর্তন মূল বিষয়।', "এর ইংরেজি প্রতিশব্দ 'Chemistry'।", "এটি 'Chemi' শব্দ থেকে এসেছে।"]

In [8]:
print(record["ExactAnswer"])

['বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদার্থের পরিবর্তন নিয়ে আলোচনা করা হয়।']

In [9]:
print(record.keys())

dict_keys(['Question', 'Hints', 'ExactAnswer', 'Candidates_Answers', 'Convergence', 'Convergence_Ranked', 'TopicTags'])

In [10]:
import json
import pandas as pd
from pathlib import Path

In [11]:
jsonl_files = list(Path("/kaggle/input").rglob("*.jsonl"))

for file in jsonl_files:
    print(file)

/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/chem/SSC_Chemistry_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/phy/SSC_Physics_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/Bio/SSC_Biology_Datasets.jsonl

In [12]:
def load_jsonl_safely(file_path, subject):
    
    valid_records = []
    error_records = []

    with open(file_path, "r", encoding="utf-8") as file:

        for line_number, line in enumerate(file, start=1):

            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)

                record["subject"] = subject
                record["source_file"] = file_path.name
                record["source_line"] = line_number

                valid_records.append(record)

            except json.JSONDecodeError as error:

                error_records.append({
                    "subject": subject,
                    "source_file": file_path.name,
                    "source_line": line_number,
                    "error": str(error),
                    "raw_text": line
                })

    return valid_records, error_records

In [13]:
all_records = []
all_errors = []

for file_path in jsonl_files:

    file_name = file_path.name.lower()

    if "biology" in file_name:
        subject = "Biology"

    elif "chemistry" in file_name:
        subject = "Chemistry"

    elif "physics" in file_name:
        subject = "Physics"

    else:
        subject = "Unknown"

    records, errors = load_jsonl_safely(
        file_path=file_path,
        subject=subject
    )

    all_records.extend(records)
    all_errors.extend(errors)

In [14]:
df = pd.DataFrame(all_records)

errors_df = pd.DataFrame(all_errors)

In [15]:
print("Valid records:", len(df))
print("Malformed records:", len(errors_df))

Valid records: 11257
Malformed records: 29

In [16]:
df.head(3)

,Question,Hints,ExactAnswer,Candidates_Answers,Convergence,Convergence_Ranked,TopicTags,subject,source_file,source_line,question,hints,Sources
0,রসায়ন কী?,"[এটি বিজ্ঞানের একটি শাখা।, পদার্থের গঠন একটি আ...","[বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদ...","[বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদ...","[{'Up to 1': 0.5, 'Up to 2': 0.65, 'Up to 3': ...","[এটি বিজ্ঞানের একটি শাখা।, পদার্থের গঠন একটি আ...","[Chemistry, Definition of Chemistry]",Chemistry,SSC_Chemistry_Dataset.jsonl,1,NaN,NaN,NaN
1,রসায়নের জনক কে?,"[তিনি মধ্যযুগের একজন প্রভাবশালী আল-কেমিস্ট।, ত...",জাবির ইবনে হাইয়ান,"[জাবির ইবনে হাইয়ান, অ্যান্টনি ল্যাভয়সিয়ে, র...","{'Up to 1': 0.6, 'Up to 2': 0.8, 'Up to 3': 0....","[তিনি মধ্যযুগের একজন প্রভাবশালী আল-কেমিস্ট।, ত...",[History of Chemistry],Chemistry,SSC_Chemistry_Dataset.jsonl,2,NaN,NaN,NaN
2,আধুনিক রসায়নের জনক কে?,[তিনি ছিলেন অষ্টাদশ শতাব্দীর একজন ফরাসি অভিজাত...,অ্যান্টনি ল্যাভয়সিয়ে,"[অ্যান্টনি ল্যাভয়সিয়ে, জাবির ইবনে হাইয়ান, স...","{'Up to 1': 0.6, 'Up to 2': 0.8, 'Up to 3': 0....",[তিনি ছিলেন অষ্টাদশ শতাব্দীর একজন ফরাসি অভিজাত...,[History of Chemistry],Chemistry,SSC_Chemistry_Dataset.jsonl,3,NaN,NaN,NaN

In [17]:
print("Dataset shape:", df.shape)

Dataset shape: (11257, 13)

In [18]:
print(df.columns.tolist())

['Question', 'Hints', 'ExactAnswer', 'Candidates_Answers', 'Convergence', 'Convergence_Ranked', 'TopicTags', 'subject', 'source_file', 'source_line', 'question', 'hints', 'Sources']

In [19]:
df["subject"].value_counts()

subject
Biology      4858
Physics      3365
Chemistry    3034
Name: count, dtype: int64

In [20]:
errors_df[
    ["subject", "source_file", "source_line", "error"]
].head(10)

,subject,source_file,source_line,error
0,Physics,SSC_Physics_Dataset.jsonl,194,"Expecting ',' delimiter: line 1 column 48 (cha..."
1,Physics,SSC_Physics_Dataset.jsonl,283,Invalid \escape: line 1 column 244 (char 243)
2,Physics,SSC_Physics_Dataset.jsonl,297,Invalid \escape: line 1 column 341 (char 340)
3,Physics,SSC_Physics_Dataset.jsonl,298,Invalid \escape: line 1 column 257 (char 256)
4,Physics,SSC_Physics_Dataset.jsonl,476,Invalid \escape: line 1 column 382 (char 381)
5,Physics,SSC_Physics_Dataset.jsonl,2181,Invalid \escape: line 1 column 395 (char 394)
6,Physics,SSC_Physics_Dataset.jsonl,2182,Invalid \escape: line 1 column 400 (char 399)
7,Physics,SSC_Physics_Dataset.jsonl,2183,Invalid \escape: line 1 column 424 (char 423)
8,Physics,SSC_Physics_Dataset.jsonl,2184,Invalid \escape: line 1 column 238 (char 237)
9,Physics,SSC_Physics_Dataset.jsonl,2187,Invalid \escape: line 1 column 175 (char 174)

In [21]:
errors_df["subject"].value_counts()

subject
Physics    28
Biology     1
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11257 entries, 0 to 11256
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Question            11246 non-null  object
 1   Hints               11246 non-null  object
 2   ExactAnswer         11257 non-null  object
 3   Candidates_Answers  11257 non-null  object
 4   Convergence         11257 non-null  object
 5   Convergence_Ranked  11257 non-null  object
 6   TopicTags           11256 non-null  object
 7   subject             11257 non-null  object
 8   source_file         11257 non-null  object
 9   source_line         11257 non-null  int64
 10  question            11 non-null     object
 11  hints               11 non-null     object
 12  Sources             10 non-null     object
dtypes: int64(1), object(12)
memory usage: 1.1+ MB

In [23]:
df["ExactAnswer"].apply(type).value_counts()

ExactAnswer
<class 'list'>    9351
<class 'str'>     1906
Name: count, dtype: int64

In [24]:
df["Hints"].apply(
    lambda x: len(x) if isinstance(x, list) else None
).value_counts(dropna=False)

Hints
5.0    10572
6.0      367
7.0      254
3.0       25
4.0       24
NaN       11
8.0        2
0.0        1
2.0        1
Name: count, dtype: int64

In [25]:
print("Valid records:", len(df))
print("Malformed records:", len(errors_df))

df["subject"].value_counts()

df.columns.tolist()

df["ExactAnswer"].apply(type).value_counts()

Valid records: 11257
Malformed records: 29

ExactAnswer
<class 'list'>    9351
<class 'str'>     1906
Name: count, dtype: int64

In [26]:
df.isna().sum().sort_values(ascending=False)

Sources               11247
question              11246
hints                 11246
Hints                    11
Question                 11
TopicTags                 1
Convergence               0
ExactAnswer               0
Candidates_Answers        0
source_file               0
subject                   0
Convergence_Ranked        0
source_line               0
dtype: int64

In [27]:
question_overlap = df[
    df["Question"].notna() &
    df["question"].notna()
]

print("Rows containing BOTH Question and question:",
      len(question_overlap))

Rows containing BOTH Question and question: 0

In [28]:
hints_overlap = df[
    df["Hints"].notna() &
    df["hints"].notna()
]

print("Rows containing BOTH Hints and hints:",
      len(hints_overlap))

Rows containing BOTH Hints and hints: 0

In [29]:
df.loc[
    df["question"].notna(),
    [
        "Question",
        "question",
        "Hints",
        "hints",
        "subject",
        "source_file",
        "source_line"
    ]
]

,Question,question,Hints,hints,subject,source_file,source_line
6467,NaN,কোন শাখা কৃষিকে উন্নত করতে নতুন জাত উদ্ভাবন ও ...,NaN,"[এটি জীববিজ্ঞানের ব্যবহারিক শাখা।, রোগ প্রতিরো...",Biology,SSC_Biology_Datasets.jsonl,69
6468,NaN,"কোন শাখার মাধ্যমে খাদ্য প্রক্রিয়াজাতকরণ, ওষুধ...",NaN,[শিল্পে উদ্ভাবন ও উৎপাদন বাড়াতে এটি ব্যবহৃত হ...,Biology,SSC_Biology_Datasets.jsonl,70
6469,NaN,কোন প্রক্রিয়ার মাধ্যমে জীববিজ্ঞান পরিবেশ রক্ষ...,NaN,"[দূষণ নিয়ন্ত্রণে সহায়ক।, বন সংরক্ষণ ও জীববৈচ...",Biology,SSC_Biology_Datasets.jsonl,71
6470,NaN,"কোন প্রক্রিয়ার মাধ্যমে ভ্যাকসিন, হরমোন ও ওষুধ...",NaN,"[চিকিৎসা ও স্বাস্থ্য উন্নয়নে অপরিহার্য।, জিন ...",Biology,SSC_Biology_Datasets.jsonl,72
6471,NaN,কোন ধরনের জীব ক্ষুদ্র অণুজীব খাদ্যপ্রক্রিয়াজা...,NaN,"[ফারমেন্টেশন প্রক্রিয়ায় সহায়ক।, দই, চিজ এবং...",Biology,SSC_Biology_Datasets.jsonl,73
6472,NaN,কোন শাখা মহাকাশে জীবনের অভিযোজন বোঝাতে সাহায্য...,NaN,[মহাকাশচারীদের শরীর মহাকর্ষহীন পরিবেশে কেমন প্...,Biology,SSC_Biology_Datasets.jsonl,74
6473,NaN,কোন প্রক্রিয়া জীববিজ্ঞানের তথ্য বিশ্লেষণ ও নত...,NaN,[কম্পিউটার বিজ্ঞান ও জীববিজ্ঞানের সমন্বিত শাখা...,Biology,SSC_Biology_Datasets.jsonl,75
6474,NaN,কোন শাখা রোগ প্রতিরোধ ক্ষমতা বোঝার জন্য গুরুত্...,NaN,[জীবদেহের রোগ প্রতিরোধ ব্যবস্থা নিয়ে গবেষণা ক...,Biology,SSC_Biology_Datasets.jsonl,76
6475,NaN,"কোন প্রক্রিয়ার মাধ্যমে পর্যবেক্ষণ, অনুমান, পর...",NaN,[প্রকৃতিতে জীব ও তাদের আচরণ পর্যবেক্ষণ করা হয়...,Biology,SSC_Biology_Datasets.jsonl,77
6476,NaN,"কোন শাখা আমাদের শরীর, স্বাস্থ্য, প্রকৃতি ও জীব...",NaN,"[শরীর ও স্বাস্থ্য সম্পর্কে গভীর ধারণা দেয়।, প...",Biology,SSC_Biology_Datasets.jsonl,78
6477,NaN,"মানব কল্যাণে কোন শাখা চিকিৎসা, কৃষি, পরিবেশ, শ...",NaN,"[নতুন ওষুধ ও ভ্যাকসিন আবিষ্কারে অবদান রাখে।, উ...",Biology,SSC_Biology_Datasets.jsonl,79

In [30]:
df_clean = df.copy()

In [31]:
df_clean["Question"] = df_clean["Question"].fillna(
    df_clean["question"]
)

In [32]:
df_clean["Hints"] = df_clean["Hints"].fillna(
    df_clean["hints"]
)

In [33]:
print("Missing Question:",
      df_clean["Question"].isna().sum())

print("Missing Hints:",
      df_clean["Hints"].isna().sum())

print("Shape:",
      df_clean.shape)

Missing Question: 0
Missing Hints: 0
Shape: (11257, 13)

In [34]:
df_clean.columns.tolist()

['Question',
 'Hints',
 'ExactAnswer',
 'Candidates_Answers',
 'Convergence',
 'Convergence_Ranked',
 'TopicTags',
 'subject',
 'source_file',
 'source_line',
 'question',
 'hints',
 'Sources']

In [35]:
df_clean.loc[
    df_clean["Sources"].notna(),
    [
        "Question",
        "Sources",
        "subject",
        "source_line"
    ]
]

,Question,Sources,subject,source_line
7596,পৌষ্টিক নালির কোন অংশে খাদ্যের কোনো পরিপাক ঘটে...,[],Biology,1198
7597,পিত্তরসের প্রধান কাজ কী?,[],Biology,1199
7598,একটি শিশুর উচ্চতা ১৫০ সে.মি. এবং ওজন ৬০ কেজি হ...,[],Biology,1200
7599,"ইউরিয়া, ইউরিক এসিড ও অ্যামোনিয়া কোথায় তৈরি হয়?",[],Biology,1201
7600,কোন খাদ্য উপাদানটি স্থূলতা হ্রাসে সহায়ক ভূমিক...,[],Biology,1202
7601,"মাছের শুঁটকিকরণ, লোনা ইলিশ, আচার তৈরি এগুলো কী...",[],Biology,1203
7602,ফল পাকানোর জন্য অননুমোদিতভাবে কোন রাসায়নিক পদা...,[],Biology,1204
7603,মর্গে লাশ সংরক্ষণে ব্যবহৃত কোন রাসায়নিক পদার্থ...,[],Biology,1205
7604,মানুষের স্থায়ী দাঁত কত প্রকার?,[],Biology,1206
7605,প্রতিটি দাঁতের মধ্যবর্তী অংশকে কী বলা হয়?,[],Biology,1207

In [36]:
df_clean["ExactAnswer"].apply(
    lambda x: len(x) if isinstance(x, list) else None
).value_counts(dropna=False)

ExactAnswer
1.0    9333
NaN    1906
2.0      16
3.0       2
Name: count, dtype: int64

In [37]:
# 1
df.isna().sum().sort_values(ascending=False)

Sources               11247
question              11246
hints                 11246
Hints                    11
Question                 11
TopicTags                 1
Convergence               0
ExactAnswer               0
Candidates_Answers        0
source_file               0
subject                   0
Convergence_Ranked        0
source_line               0
dtype: int64

In [38]:
# 2
question_overlap = df[
    df["Question"].notna() &
    df["question"].notna()
]

print(len(question_overlap))

0

In [39]:
# 3
hints_overlap = df[
    df["Hints"].notna() &
    df["hints"].notna()
]

print(len(hints_overlap))

0

In [40]:
# 4
df.loc[
    df["question"].notna(),
    ["Question", "question", "Hints", "hints",
     "subject", "source_file", "source_line"]
]

,Question,question,Hints,hints,subject,source_file,source_line
6467,NaN,কোন শাখা কৃষিকে উন্নত করতে নতুন জাত উদ্ভাবন ও ...,NaN,"[এটি জীববিজ্ঞানের ব্যবহারিক শাখা।, রোগ প্রতিরো...",Biology,SSC_Biology_Datasets.jsonl,69
6468,NaN,"কোন শাখার মাধ্যমে খাদ্য প্রক্রিয়াজাতকরণ, ওষুধ...",NaN,[শিল্পে উদ্ভাবন ও উৎপাদন বাড়াতে এটি ব্যবহৃত হ...,Biology,SSC_Biology_Datasets.jsonl,70
6469,NaN,কোন প্রক্রিয়ার মাধ্যমে জীববিজ্ঞান পরিবেশ রক্ষ...,NaN,"[দূষণ নিয়ন্ত্রণে সহায়ক।, বন সংরক্ষণ ও জীববৈচ...",Biology,SSC_Biology_Datasets.jsonl,71
6470,NaN,"কোন প্রক্রিয়ার মাধ্যমে ভ্যাকসিন, হরমোন ও ওষুধ...",NaN,"[চিকিৎসা ও স্বাস্থ্য উন্নয়নে অপরিহার্য।, জিন ...",Biology,SSC_Biology_Datasets.jsonl,72
6471,NaN,কোন ধরনের জীব ক্ষুদ্র অণুজীব খাদ্যপ্রক্রিয়াজা...,NaN,"[ফারমেন্টেশন প্রক্রিয়ায় সহায়ক।, দই, চিজ এবং...",Biology,SSC_Biology_Datasets.jsonl,73
6472,NaN,কোন শাখা মহাকাশে জীবনের অভিযোজন বোঝাতে সাহায্য...,NaN,[মহাকাশচারীদের শরীর মহাকর্ষহীন পরিবেশে কেমন প্...,Biology,SSC_Biology_Datasets.jsonl,74
6473,NaN,কোন প্রক্রিয়া জীববিজ্ঞানের তথ্য বিশ্লেষণ ও নত...,NaN,[কম্পিউটার বিজ্ঞান ও জীববিজ্ঞানের সমন্বিত শাখা...,Biology,SSC_Biology_Datasets.jsonl,75
6474,NaN,কোন শাখা রোগ প্রতিরোধ ক্ষমতা বোঝার জন্য গুরুত্...,NaN,[জীবদেহের রোগ প্রতিরোধ ব্যবস্থা নিয়ে গবেষণা ক...,Biology,SSC_Biology_Datasets.jsonl,76
6475,NaN,"কোন প্রক্রিয়ার মাধ্যমে পর্যবেক্ষণ, অনুমান, পর...",NaN,[প্রকৃতিতে জীব ও তাদের আচরণ পর্যবেক্ষণ করা হয়...,Biology,SSC_Biology_Datasets.jsonl,77
6476,NaN,"কোন শাখা আমাদের শরীর, স্বাস্থ্য, প্রকৃতি ও জীব...",NaN,"[শরীর ও স্বাস্থ্য সম্পর্কে গভীর ধারণা দেয়।, প...",Biology,SSC_Biology_Datasets.jsonl,78
6477,NaN,"মানব কল্যাণে কোন শাখা চিকিৎসা, কৃষি, পরিবেশ, শ...",NaN,"[নতুন ওষুধ ও ভ্যাকসিন আবিষ্কারে অবদান রাখে।, উ...",Biology,SSC_Biology_Datasets.jsonl,79

In [41]:
# 5
df["ExactAnswer"].apply(
    lambda x: len(x) if isinstance(x, list) else None
).value_counts(dropna=False)

ExactAnswer
1.0    9333
NaN    1906
2.0      16
3.0       2
Name: count, dtype: int64

In [42]:
df_clean = df.copy()

In [43]:
df_clean["Question"] = df_clean["Question"].fillna(
    df_clean["question"]
)

df_clean["Hints"] = df_clean["Hints"].fillna(
    df_clean["hints"]
)

In [44]:
print("Missing Question:", df_clean["Question"].isna().sum())
print("Missing Hints:", df_clean["Hints"].isna().sum())

print("Shape:", df_clean.shape)
print(df_clean.columns.tolist())

Missing Question: 0
Missing Hints: 0
Shape: (11257, 13)
['Question', 'Hints', 'ExactAnswer', 'Candidates_Answers', 'Convergence', 'Convergence_Ranked', 'TopicTags', 'subject', 'source_file', 'source_line', 'question', 'hints', 'Sources']

In [45]:
multi_answer_rows = df_clean[
    df_clean["ExactAnswer"].apply(
        lambda x: isinstance(x, list) and len(x) > 1
    )
]

print("Rows with multiple answers:", len(multi_answer_rows))

Rows with multiple answers: 18

In [46]:
multi_answer_rows[
    [
        "Question",
        "ExactAnswer",
        "subject",
        "source_file",
        "source_line"
    ]
]

,Question,ExactAnswer,subject,source_file,source_line
6429,প্রাণীর শ্রেণিবিন্যাসে সবচেয়ে বড় স্তর কোনটি?,"[রাজ্য , Kingdom]",Biology,SSC_Biology_Datasets.jsonl,31
6430,শ্রেণিবিন্যাসের ক্ষুদ্রতম স্তর কোনটি?,"[প্রজাতি , Species]",Biology,SSC_Biology_Datasets.jsonl,32
6438,"জীববিজ্ঞানের যে শাখাটি প্রাণীদের গঠন, কাজ ও শ্...","[প্রাণীবিজ্ঞান শারীরস্থানবিদ্যা, প্রাণী শ্রেণি...",Biology,SSC_Biology_Datasets.jsonl,40
6439,"কোন শাখাটি উদ্ভিদের গঠন, জীবনচক্র ও পরিবেশের স...","[উদ্ভিদবিজ্ঞান শ্রেণিবিন্যাস, উদ্ভিদ শারীরবৃত্...",Biology,SSC_Biology_Datasets.jsonl,41
6467,কোন শাখা কৃষিকে উন্নত করতে নতুন জাত উদ্ভাবন ও ...,"[কৃষি জীববিজ্ঞান, Agricultural Biology]",Biology,SSC_Biology_Datasets.jsonl,69
6468,"কোন শাখার মাধ্যমে খাদ্য প্রক্রিয়াজাতকরণ, ওষুধ...","[শিল্প জীববিজ্ঞান, Industrial Biotechnology]",Biology,SSC_Biology_Datasets.jsonl,70
6469,কোন প্রক্রিয়ার মাধ্যমে জীববিজ্ঞান পরিবেশ রক্ষ...,"[পরিবেশ জীববিজ্ঞান , Environmental Biology]",Biology,SSC_Biology_Datasets.jsonl,71
6470,"কোন প্রক্রিয়ার মাধ্যমে ভ্যাকসিন, হরমোন ও ওষুধ...","[চিকিৎসা জীববিজ্ঞান , Medical Biotechnology]",Biology,SSC_Biology_Datasets.jsonl,72
6471,কোন ধরনের জীব ক্ষুদ্র অণুজীব খাদ্যপ্রক্রিয়াজা...,"[অণুজীব , Microorganisms]",Biology,SSC_Biology_Datasets.jsonl,73
6472,কোন শাখা মহাকাশে জীবনের অভিযোজন বোঝাতে সাহায্য...,"[মহাকাশ জীববিজ্ঞান , Space Biology]",Biology,SSC_Biology_Datasets.jsonl,74
6473,কোন প্রক্রিয়া জীববিজ্ঞানের তথ্য বিশ্লেষণ ও নত...,"[বায়োইনফরমেটিক্স , Bioinformatics]",Biology,SSC_Biology_Datasets.jsonl,75
6474,কোন শাখা রোগ প্রতিরোধ ক্ষমতা বোঝার জন্য গুরুত্...,"[ইমিউনোলজি , Immunology]",Biology,SSC_Biology_Datasets.jsonl,76
6475,"কোন প্রক্রিয়ার মাধ্যমে পর্যবেক্ষণ, অনুমান, পর...","[বৈজ্ঞানিক গবেষণা প্রক্রিয়া , Scientific Res...",Biology,SSC_Biology_Datasets.jsonl,77
6476,"কোন শাখা আমাদের শরীর, স্বাস্থ্য, প্রকৃতি ও জীব...","[জীববিজ্ঞান , Biology]",Biology,SSC_Biology_Datasets.jsonl,78
6477,"মানব কল্যাণে কোন শাখা চিকিৎসা, কৃষি, পরিবেশ, শ...","[জীববিজ্ঞান , Biology]",Biology,SSC_Biology_Datasets.jsonl,79
7815,একজন সুস্থ প্রাপ্তবয়স্ক মানুষের রক্তের স্বাভা...,"[৩৭ ডিগ্রি সেলসিয়াস , ৯৮.৪° ফারেনহাইট]",Biology,SSC_Biology_Datasets.jsonl,1417
9202,সবাত শ্বসন প্রক্রিয়া কোষের কোন দুটি স্থানে সং...,"[সাইটোপ্লাজম, মাইটোকন্ড্রিয়া]",Biology,SSC_Biology_Datasets.jsonl,2804
9907,কৃত্রিম ভেজিটেটিভ প্রজননের উদাহরণ কী?,"[কলম, গ্রাফটিং]",Biology,SSC_Biology_Datasets.jsonl,3510

In [47]:
lambda x: isinstance(x, list) and len(x) > 1

In [48]:
string_answer_rows = df_clean[
    df_clean["ExactAnswer"].apply(
        lambda x: isinstance(x, str)
    )
]

print("String answer rows:", len(string_answer_rows))

String answer rows: 1906

In [49]:
string_answer_rows[
    [
        "Question",
        "ExactAnswer",
        "subject",
        "source_line"
    ]
].head(20)

,Question,ExactAnswer,subject,source_line
1,রসায়নের জনক কে?,জাবির ইবনে হাইয়ান,Chemistry,2
2,আধুনিক রসায়নের জনক কে?,অ্যান্টনি ল্যাভয়সিয়ে,Chemistry,3
3,রসায়নের গবেষণার দ্বিতীয় ধাপ কোনটি?,পর্যবেক্ষণ ও তথ্য সংগ্রহ,Chemistry,4
4,কোনটি 'বিষাক্ত' রাসায়নিক পদার্থের সাংকেতিক চি...,একটি খুলি ও দুটি হাড়ের চিহ্ন,Chemistry,5
5,কোন ধরনের রাসায়নিক পদার্থ 'দাহ্য' হিসেবে চিহ্...,দাহ্য পদার্থ,Chemistry,6
6,রাসায়নিক গবেষণায় ব্যবহৃত গ্লাভস কী ধরনের পদা...,ল্যাটেক্স বা নাইট্রাইল,Chemistry,7
7,গবেষণাগারে ব্যবহৃত কোনো রাসায়নিক পদার্থ ত্বকে...,প্রচুর পানি দিয়ে ধৌত করা,Chemistry,8
8,রসায়ন কোন দুটি ধাতু ব্যবহারের মাধ্যমে প্রথম চ...,সোনা ও ব্রোঞ্জ,Chemistry,9
9,পরিবেশ ও উন্নয়ন সম্মেলনের প্রধান বিষয়বস্তু ক...,রাসায়নিক পদার্থের ঝুঁকির মাত্রা ও সতর্কতা,Chemistry,10
10,রসায়ন গবেষণার চতুর্থ ধাপ কোনটি?,ফলাফল বিশ্লেষণ,Chemistry,11
11,রসায়ন গবেষণার পঞ্চম ধাপ কোনটি?,সিদ্ধান্ত গ্রহণ,Chemistry,12
12,কোন ধরনের রাসায়নিক বর্জ্য পুনঃচক্রায়ন (recyc...,ইলেকট্রনিক বর্জ্য (e-waste),Chemistry,13
13,কাগজ উৎপাদনে রসায়নের কোন নীতি ব্যবহার করা হয়?,রাসায়নিক প্রক্রিয়া,Chemistry,14
14,কোন শিল্পে কাঁচামাল হিসেবে পেট্রোলিয়াম ব্যবহৃ...,পেট্রোকেমিক্যাল শিল্প,Chemistry,15
15,সাবান ও ডিটারজেন্ট তৈরিতে রসায়নের কোন শাখা জড...,পরিষ্কারক শিল্প,Chemistry,16
16,কৃষি ক্ষেত্রে ব্যবহৃত রাসায়নিক সার তৈরিতে কোন...,রাসায়নিক সার শিল্প,Chemistry,17
17,রসায়ন গবেষণার প্রথম ধাপ কোনটি?,সমস্যা শনাক্তকরণ,Chemistry,18
18,রাসায়নিক দ্রবের 'জ্বালানি' চিহ্নটি কেমন?,গ্যাস সিলিন্ডারের চিহ্ন,Chemistry,19
19,রাসায়নিক দ্রবের 'বিস্ফোরক' চিহ্নটি কেমন?,বিস্ফোরিত বস্তুর চিত্র,Chemistry,20
20,রসায়ন কাকে বলে?,"বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদা...",Chemistry,21

In [50]:
empty_answer_lists = df_clean[
    df_clean["ExactAnswer"].apply(
        lambda x: isinstance(x, list) and len(x) == 0
    )
]

print("Empty answer lists:", len(empty_answer_lists))

Empty answer lists: 0

In [51]:
source_rows = df_clean[
    df_clean["Sources"].notna()
]

print("Rows containing Sources:", len(source_rows))

Rows containing Sources: 10

In [52]:
source_rows[
    [
        "Question",
        "Sources",
        "subject",
        "source_file",
        "source_line"
    ]
]

,Question,Sources,subject,source_file,source_line
7596,পৌষ্টিক নালির কোন অংশে খাদ্যের কোনো পরিপাক ঘটে...,[],Biology,SSC_Biology_Datasets.jsonl,1198
7597,পিত্তরসের প্রধান কাজ কী?,[],Biology,SSC_Biology_Datasets.jsonl,1199
7598,একটি শিশুর উচ্চতা ১৫০ সে.মি. এবং ওজন ৬০ কেজি হ...,[],Biology,SSC_Biology_Datasets.jsonl,1200
7599,"ইউরিয়া, ইউরিক এসিড ও অ্যামোনিয়া কোথায় তৈরি হয়?",[],Biology,SSC_Biology_Datasets.jsonl,1201
7600,কোন খাদ্য উপাদানটি স্থূলতা হ্রাসে সহায়ক ভূমিক...,[],Biology,SSC_Biology_Datasets.jsonl,1202
7601,"মাছের শুঁটকিকরণ, লোনা ইলিশ, আচার তৈরি এগুলো কী...",[],Biology,SSC_Biology_Datasets.jsonl,1203
7602,ফল পাকানোর জন্য অননুমোদিতভাবে কোন রাসায়নিক পদা...,[],Biology,SSC_Biology_Datasets.jsonl,1204
7603,মর্গে লাশ সংরক্ষণে ব্যবহৃত কোন রাসায়নিক পদার্থ...,[],Biology,SSC_Biology_Datasets.jsonl,1205
7604,মানুষের স্থায়ী দাঁত কত প্রকার?,[],Biology,SSC_Biology_Datasets.jsonl,1206
7605,প্রতিটি দাঁতের মধ্যবর্তী অংশকে কী বলা হয়?,[],Biology,SSC_Biology_Datasets.jsonl,1207

In [53]:
missing_topic = df_clean[
    df_clean["TopicTags"].isna()
]

missing_topic[
    [
        "Question",
        "Hints",
        "ExactAnswer",
        "subject",
        "source_file",
        "source_line"
    ]
]

,Question,Hints,ExactAnswer,subject,source_file,source_line
2582,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,"[পেট্রোল ফলন বাড়ানোর মূল প্রযুক্তি।, উচ্চ তাপ...",[ক্র্যাকিং],Chemistry,SSC_Chemistry_Dataset.jsonl,2583

In [54]:
df_clean["Hints"].apply(
    lambda x: len(x) if isinstance(x, list) else None
).value_counts(dropna=False).sort_index()

Hints
0        1
2        1
3       25
4       24
5    10583
6      367
7      254
8        2
Name: count, dtype: int64

In [55]:
zero_hint_rows = df_clean[
    df_clean["Hints"].apply(
        lambda x: isinstance(x, list) and len(x) == 0
    )
]

zero_hint_rows[
    [
        "Question",
        "Hints",
        "ExactAnswer",
        "subject",
        "source_line"
    ]
]

,Question,Hints,ExactAnswer,subject,source_line
1939,দ্রাব্যতা গুণফল (Ksp) কাকে বলে?,[],[কম দ্রবণীয় লবণের সমতার আয়ন গুণফল।],Chemistry,1940

In [56]:
print("Missing Question:", df_clean["Question"].isna().sum())
print("Missing Hints:", df_clean["Hints"].isna().sum())
print("Shape:", df_clean.shape)

Missing Question: 0
Missing Hints: 0
Shape: (11257, 13)

In [57]:
multi_answer_rows[
    ["Question", "ExactAnswer", "subject", "source_line"]
]

,Question,ExactAnswer,subject,source_line
6429,প্রাণীর শ্রেণিবিন্যাসে সবচেয়ে বড় স্তর কোনটি?,"[রাজ্য , Kingdom]",Biology,31
6430,শ্রেণিবিন্যাসের ক্ষুদ্রতম স্তর কোনটি?,"[প্রজাতি , Species]",Biology,32
6438,"জীববিজ্ঞানের যে শাখাটি প্রাণীদের গঠন, কাজ ও শ্...","[প্রাণীবিজ্ঞান শারীরস্থানবিদ্যা, প্রাণী শ্রেণি...",Biology,40
6439,"কোন শাখাটি উদ্ভিদের গঠন, জীবনচক্র ও পরিবেশের স...","[উদ্ভিদবিজ্ঞান শ্রেণিবিন্যাস, উদ্ভিদ শারীরবৃত্...",Biology,41
6467,কোন শাখা কৃষিকে উন্নত করতে নতুন জাত উদ্ভাবন ও ...,"[কৃষি জীববিজ্ঞান, Agricultural Biology]",Biology,69
6468,"কোন শাখার মাধ্যমে খাদ্য প্রক্রিয়াজাতকরণ, ওষুধ...","[শিল্প জীববিজ্ঞান, Industrial Biotechnology]",Biology,70
6469,কোন প্রক্রিয়ার মাধ্যমে জীববিজ্ঞান পরিবেশ রক্ষ...,"[পরিবেশ জীববিজ্ঞান , Environmental Biology]",Biology,71
6470,"কোন প্রক্রিয়ার মাধ্যমে ভ্যাকসিন, হরমোন ও ওষুধ...","[চিকিৎসা জীববিজ্ঞান , Medical Biotechnology]",Biology,72
6471,কোন ধরনের জীব ক্ষুদ্র অণুজীব খাদ্যপ্রক্রিয়াজা...,"[অণুজীব , Microorganisms]",Biology,73
6472,কোন শাখা মহাকাশে জীবনের অভিযোজন বোঝাতে সাহায্য...,"[মহাকাশ জীববিজ্ঞান , Space Biology]",Biology,74
6473,কোন প্রক্রিয়া জীববিজ্ঞানের তথ্য বিশ্লেষণ ও নত...,"[বায়োইনফরমেটিক্স , Bioinformatics]",Biology,75
6474,কোন শাখা রোগ প্রতিরোধ ক্ষমতা বোঝার জন্য গুরুত্...,"[ইমিউনোলজি , Immunology]",Biology,76
6475,"কোন প্রক্রিয়ার মাধ্যমে পর্যবেক্ষণ, অনুমান, পর...","[বৈজ্ঞানিক গবেষণা প্রক্রিয়া , Scientific Res...",Biology,77
6476,"কোন শাখা আমাদের শরীর, স্বাস্থ্য, প্রকৃতি ও জীব...","[জীববিজ্ঞান , Biology]",Biology,78
6477,"মানব কল্যাণে কোন শাখা চিকিৎসা, কৃষি, পরিবেশ, শ...","[জীববিজ্ঞান , Biology]",Biology,79
7815,একজন সুস্থ প্রাপ্তবয়স্ক মানুষের রক্তের স্বাভা...,"[৩৭ ডিগ্রি সেলসিয়াস , ৯৮.৪° ফারেনহাইট]",Biology,1417
9202,সবাত শ্বসন প্রক্রিয়া কোষের কোন দুটি স্থানে সং...,"[সাইটোপ্লাজম, মাইটোকন্ড্রিয়া]",Biology,2804
9907,কৃত্রিম ভেজিটেটিভ প্রজননের উদাহরণ কী?,"[কলম, গ্রাফটিং]",Biology,3510

In [58]:
source_rows[
    ["Question", "Sources", "subject", "source_line"]
]

,Question,Sources,subject,source_line
7596,পৌষ্টিক নালির কোন অংশে খাদ্যের কোনো পরিপাক ঘটে...,[],Biology,1198
7597,পিত্তরসের প্রধান কাজ কী?,[],Biology,1199
7598,একটি শিশুর উচ্চতা ১৫০ সে.মি. এবং ওজন ৬০ কেজি হ...,[],Biology,1200
7599,"ইউরিয়া, ইউরিক এসিড ও অ্যামোনিয়া কোথায় তৈরি হয়?",[],Biology,1201
7600,কোন খাদ্য উপাদানটি স্থূলতা হ্রাসে সহায়ক ভূমিক...,[],Biology,1202
7601,"মাছের শুঁটকিকরণ, লোনা ইলিশ, আচার তৈরি এগুলো কী...",[],Biology,1203
7602,ফল পাকানোর জন্য অননুমোদিতভাবে কোন রাসায়নিক পদা...,[],Biology,1204
7603,মর্গে লাশ সংরক্ষণে ব্যবহৃত কোন রাসায়নিক পদার্থ...,[],Biology,1205
7604,মানুষের স্থায়ী দাঁত কত প্রকার?,[],Biology,1206
7605,প্রতিটি দাঁতের মধ্যবর্তী অংশকে কী বলা হয়?,[],Biology,1207

In [59]:
missing_topic[
    ["Question", "ExactAnswer", "subject", "source_line"]
]

,Question,ExactAnswer,subject,source_line
2582,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,[ক্র্যাকিং],Chemistry,2583

In [60]:
df_clean["ExactAnswer"].apply(type).value_counts()

ExactAnswer
<class 'list'>    9351
<class 'str'>     1906
Name: count, dtype: int64

In [61]:
def normalize_exact_answer(value):

    if isinstance(value, list):
        return value

    if isinstance(value, str):
        return [value]

    return value

In [62]:
df_clean["ExactAnswer"] = df_clean["ExactAnswer"].apply(
    normalize_exact_answer
)

In [63]:
df_clean["ExactAnswer"].apply(type).value_counts()

ExactAnswer
<class 'list'>    11257
Name: count, dtype: int64

In [64]:
df_clean["ExactAnswer"].apply(len).value_counts().sort_index()

ExactAnswer
1    11239
2       16
3        2
Name: count, dtype: int64

In [65]:
df_clean.loc[
    df_clean["Sources"].notna(),
    "Sources"
].apply(
    lambda x: isinstance(x, list) and len(x) == 0
).value_counts()

Sources
False    10
Name: count, dtype: int64

In [66]:
df_clean = df_clean.drop(
    columns=["Sources"]
)

In [67]:
print(df_clean.shape)
print(df_clean.columns.tolist())

(11257, 12)
['Question', 'Hints', 'ExactAnswer', 'Candidates_Answers', 'Convergence', 'Convergence_Ranked', 'TopicTags', 'subject', 'source_file', 'source_line', 'question', 'hints']

In [68]:
df_clean.loc[
    (df_clean["source_file"] == "SSC_Chemistry_Dataset.jsonl") &
    (df_clean["source_line"].between(2578, 2588)),
    [
        "source_line",
        "Question",
        "ExactAnswer",
        "TopicTags"
    ]
]

,source_line,Question,ExactAnswer,TopicTags
2577,2578,অ্যালকিনে পলিমারাইজেশনের সূচনা করতে ব্যবহৃত পদ...,[ইনিশিয়েটর (ফ্রি-র‌্যাডিক্যাল ইনিশিয়েটর)],"[Recycling, Plastics]"
2578,2579,প্লাস্টিক পুনঃব্যবহারযোগ্য কিনা বোঝাতে যে প্রত...,[রিসাইক্লিং কোড],"[Gas Processing, Safety]"
2579,2580,প্রাকৃতিক গ্যাসের সালফার অপসারণ প্রক্রিয়ার সাধ...,[গ্যাস সুইটেনিং],"[CNG, Transport Fuels]"
2580,2581,সংকুচিত প্রাকৃতিক গ্যাসের সংক্ষিপ্ত রূপ কী?,[CNG],"[Kerosene, Fractions]"
2581,2582,কাঁচা তেলের যে অংশটি কেরোসিন নামে পরিচিত—এটি ক...,[মিডল ডিস্টিলেট (কেরোসিন)],"[Cracking, Refining]"
2582,2583,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,[ক্র্যাকিং],NaN
2583,2584,তরল জ্বালানি থেকে গ্যাসীয় জ্বালানিতে রূপান্তর...,[রিফর্মিং (ক্যাটালিটিক রিফর্মিং)],"[Reforming, Refining]"
2584,2585,পৃথিবীর অভ্যন্তরে জৈব অবশিষ্ট থেকে গঠিত জ্বালা...,[জীবাশ্ম জ্বালানি],"[Fossil Fuels, Energy Basics]"
2585,2586,জলাভূমির উদ্ভিদাবশেষ আংশিক রূপান্তরে যে কঠিন জ...,[পিট],"[Coalification, Fossil Fuels]"
2586,2587,কয়লার সর্বোচ্চ কার্বন-সমৃদ্ধ ও ক্যালরিফিক মান...,[অ্যানথ্রাসাইট],"[Coal Types, Energy Density]"
2587,2588,অপরিশোধিত তেলকে ভগ্নাংশে আলাদা করার শিল্পপ্রক্...,[ভগ্নাংশীয় পাতন],"[Refining, Separation Processes]"

In [69]:
df_clean["TopicTags"].apply(type).value_counts(dropna=False)

TopicTags
<class 'list'>     11256
<class 'float'>        1
Name: count, dtype: int64

In [70]:
hint_counts = df_clean["Hints"].apply(
    lambda x: len(x) if isinstance(x, list) else None
)

hint_counts.value_counts(
    dropna=False
).sort_index()

Hints
0        1
2        1
3       25
4       24
5    10583
6      367
7      254
8        2
Name: count, dtype: int64

In [71]:
print(
    df_clean["ExactAnswer"]
    .apply(type)
    .value_counts()
)

print(
    df_clean["ExactAnswer"]
    .apply(len)
    .value_counts()
    .sort_index()
)

ExactAnswer
<class 'list'>    11257
Name: count, dtype: int64
ExactAnswer
1    11239
2       16
3        2
Name: count, dtype: int64

In [72]:
df_clean.loc[
    (df_clean["source_file"] == "SSC_Chemistry_Dataset.jsonl") &
    (df_clean["source_line"].between(2578, 2588)),
    ["source_line", "Question", "ExactAnswer", "TopicTags"]
]

,source_line,Question,ExactAnswer,TopicTags
2577,2578,অ্যালকিনে পলিমারাইজেশনের সূচনা করতে ব্যবহৃত পদ...,[ইনিশিয়েটর (ফ্রি-র‌্যাডিক্যাল ইনিশিয়েটর)],"[Recycling, Plastics]"
2578,2579,প্লাস্টিক পুনঃব্যবহারযোগ্য কিনা বোঝাতে যে প্রত...,[রিসাইক্লিং কোড],"[Gas Processing, Safety]"
2579,2580,প্রাকৃতিক গ্যাসের সালফার অপসারণ প্রক্রিয়ার সাধ...,[গ্যাস সুইটেনিং],"[CNG, Transport Fuels]"
2580,2581,সংকুচিত প্রাকৃতিক গ্যাসের সংক্ষিপ্ত রূপ কী?,[CNG],"[Kerosene, Fractions]"
2581,2582,কাঁচা তেলের যে অংশটি কেরোসিন নামে পরিচিত—এটি ক...,[মিডল ডিস্টিলেট (কেরোসিন)],"[Cracking, Refining]"
2582,2583,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,[ক্র্যাকিং],NaN
2583,2584,তরল জ্বালানি থেকে গ্যাসীয় জ্বালানিতে রূপান্তর...,[রিফর্মিং (ক্যাটালিটিক রিফর্মিং)],"[Reforming, Refining]"
2584,2585,পৃথিবীর অভ্যন্তরে জৈব অবশিষ্ট থেকে গঠিত জ্বালা...,[জীবাশ্ম জ্বালানি],"[Fossil Fuels, Energy Basics]"
2585,2586,জলাভূমির উদ্ভিদাবশেষ আংশিক রূপান্তরে যে কঠিন জ...,[পিট],"[Coalification, Fossil Fuels]"
2586,2587,কয়লার সর্বোচ্চ কার্বন-সমৃদ্ধ ও ক্যালরিফিক মান...,[অ্যানথ্রাসাইট],"[Coal Types, Energy Density]"
2587,2588,অপরিশোধিত তেলকে ভগ্নাংশে আলাদা করার শিল্পপ্রক্...,[ভগ্নাংশীয় পাতন],"[Refining, Separation Processes]"

In [73]:
df_clean["TopicTags"].apply(type).value_counts(dropna=False)

TopicTags
<class 'list'>     11256
<class 'float'>        1
Name: count, dtype: int64

In [74]:
df_clean["TopicTags_original"] = df_clean["TopicTags"].apply(
    lambda x: x.copy() if isinstance(x, list) else x
)

In [75]:
lambda x: x.copy() if isinstance(x, list) else x

In [76]:
chemistry_shift_block = df_clean.loc[
    (df_clean["source_file"] == "SSC_Chemistry_Dataset.jsonl") &
    (df_clean["source_line"].between(2554, 2583)),
    [
        "source_line",
        "Question",
        "ExactAnswer",
        "TopicTags_original"
    ]
].copy()

chemistry_shift_block

,source_line,Question,ExactAnswer,TopicTags_original
2553,2554,অপরিশোধিত তেলকে ভগ্নাংশে আলাদা করার শিল্পপ্রক্...,[ভগ্নাংশীয় পাতন],"[Coal, Fossil Fuels]"
2554,2555,অদাহ্য উপাদান কমাতে কয়লার উচ্চতর গ্রেড কোনটি?,[অ্যানথ্রাসাইট],"[Alkanes, Organic]"
2555,2556,সমসংযোজী কার্বন–হাইড্রোজেনের সম্পৃক্ত শ্রেণীটি...,[অ্যালকেন],"[Alkenes, Organic]"
2556,2557,দ্বিবন্ধনযুক্ত অসম্পৃক্ত শ্রেণীটির নাম কী?,[অ্যালকিন],"[Alkynes, Organic]"
2557,2558,ত্রিবন্ধনযুক্ত অসম্পৃক্ত শ্রেণীটির নাম কী?,[অ্যালকাইন],"[Refining, Cracking]"
2558,2559,অপরিশোধিত তেলে ভগ্নাংশ ভেঙে ছোট অণু বানানোর প্...,[ক্র্যাকিং],"[LPG, Fuels]"
2559,2560,তরল পেট্রোলিয়াম গ্যাসের সংক্ষিপ্ত নাম কী?,[LPG],"[Gas Safety, Natural Gas]"
2560,2561,প্রাকৃতিক গ্যাসে দুর্গন্ধ যুক্ত করতে যে যৌগ যো...,[মার্কাপটান (থিওল)],"[Petroleum Fractions, Fuels]"
2561,2562,"কাঁচ তৈরি ও ধাতু গলাতে ব্যবহৃত, কেরোসিনের ওপরে...",[ফুয়েল অয়েল (মিডল/হেভি ডিস্টিলেট অংশ)],"[Organic Reactions, Alkanes]"
2562,2563,অ্যালকেন থেকে হ্যালোজেন যোগে যে বিক্রিয়া ঘটে ত...,[হ্যালোজেনেশন (প্রতিস্থাপন)],"[Qualitative Tests, Alkenes]"
2563,2564,অ্যালকিনের দ্রুত শনাক্তকরণে যে রিএজেন্ট কমলা-ল...,[ব্রোমিন পানি],"[Alkanes, Nomenclature]"
2564,2565,অ্যালকেনের আরেক নাম (প্রচলিত) কী?,[প্যারাফিন],"[LPG, Fractions]"
2565,2566,"অপরিশোধিত তেলের সবচেয়ে হালকা ভগ্নাংশ, গ্যাস রা...",[এলপিজি (প্রোপেন–বিউটেন মিশ্রণ)],"[Gasoline, Transport Fuels]"
2566,2567,গ্যাসোলিনের আরেক প্রচলিত নাম কী?,[পেট্রোল],"[Addition Reactions, Catalysis]"
2567,2568,তাপ না বাড়িয়ে জৈব পদার্থে হাইড্রোজেন জুড়ার প্র...,[হাইড্রোজেনেশন (সংযোজন)],"[Polymers, Materials]"
2568,2569,দীর্ঘ শৃঙ্খল মনোমার থেকে বিশাল অণু তৈরির প্রক্...,[পলিমারাইজেশন],"[Polyethylene, Monomers]"
2569,2570,ইথিন মনোমার থেকে গঠিত প্রচলিত প্লাস্টিকের নাম কী?,[পলিথিন (পলিইথিলিন)],"[Natural Gas, Transport]"
2570,2571,প্রাকৃতিক গ্যাসকে তরল করে দূরপাল্লায় বহনে যে ন...,[LNG (Liquefied Natural Gas)],"[Fuels, Engines]"
2571,2572,জ্বালানিতে নকিং কমাতে ব্যবহৃত পরিমাপক সূচকের ন...,[অক্টেন সংখ্যা],"[Bitumen, Fractions]"
2572,2573,"অপরিশোধিত তেলের গাঢ়, আঠালো সবচেয়ে ভারী অবশিষ্ট...",[বিটুমেন],"[Coalification, Coal]"
2573,2574,"কয়লা গঠনের প্রাথমিক, পানি-সমৃদ্ধ ও কম কার্বনযু...",[পিট],"[Petroleum Geology, Reservoirs]"
2574,2575,ভূগর্ভস্থ শিলার রন্ধ্রে আটকে থাকা তেল/গ্যাসকে ...,[ক্যাপ রক (কভার শিলা)],"[Upstream Processing, Refining]"
2575,2576,তেল কূপ থেকে উঠে আসা পানি অপসারণসহ প্রাথমিক প্...,[ডিহাইড্রেশন/ডিস্যাল্টিং (প্রাথমিক ট্রিটমেন্ট)],"[Laboratory, Solvents]"
2576,2577,পেট্রোলিয়াম ইথারের প্রধান ব্যবহার কী—এক/দুই শব...,[দ্রাবক (ডিগ্রিজিং)],"[Polymerization, Kinetics]"
2577,2578,অ্যালকিনে পলিমারাইজেশনের সূচনা করতে ব্যবহৃত পদ...,[ইনিশিয়েটর (ফ্রি-র‌্যাডিক্যাল ইনিশিয়েটর)],"[Recycling, Plastics]"
2578,2579,প্লাস্টিক পুনঃব্যবহারযোগ্য কিনা বোঝাতে যে প্রত...,[রিসাইক্লিং কোড],"[Gas Processing, Safety]"
2579,2580,প্রাকৃতিক গ্যাসের সালফার অপসারণ প্রক্রিয়ার সাধ...,[গ্যাস সুইটেনিং],"[CNG, Transport Fuels]"
2580,2581,সংকুচিত প্রাকৃতিক গ্যাসের সংক্ষিপ্ত রূপ কী?,[CNG],"[Kerosene, Fractions]"
2581,2582,কাঁচা তেলের যে অংশটি কেরোসিন নামে পরিচিত—এটি ক...,[মিডল ডিস্টিলেট (কেরোসিন)],"[Cracking, Refining]"
2582,2583,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,[ক্র্যাকিং],NaN

In [77]:
def get_chemistry_index(line_number):

    mask = (
        (df_clean["source_file"] == "SSC_Chemistry_Dataset.jsonl") &
        (df_clean["source_line"] == line_number)
    )

    return df_clean.index[mask][0]

In [78]:
for line_number in range(2555, 2584):

    previous_index = get_chemistry_index(line_number - 1)
    current_index = get_chemistry_index(line_number)

    previous_tags = df_clean.at[
        previous_index,
        "TopicTags_original"
    ]

    df_clean.at[
        current_index,
        "TopicTags"
    ] = previous_tags.copy()

In [79]:
target_index = get_chemistry_index(2554)
reference_index = get_chemistry_index(2588)

reference_tags = df_clean.at[
    reference_index,
    "TopicTags_original"
]

df_clean.at[
    target_index,
    "TopicTags"
] = reference_tags.copy()

In [80]:
df_clean.loc[
    (df_clean["source_file"] == "SSC_Chemistry_Dataset.jsonl") &
    (df_clean["source_line"].between(2554, 2584)),
    [
        "source_line",
        "Question",
        "TopicTags_original",
        "TopicTags"
    ]
]

,source_line,Question,TopicTags_original,TopicTags
2553,2554,অপরিশোধিত তেলকে ভগ্নাংশে আলাদা করার শিল্পপ্রক্...,"[Coal, Fossil Fuels]","[Refining, Separation Processes]"
2554,2555,অদাহ্য উপাদান কমাতে কয়লার উচ্চতর গ্রেড কোনটি?,"[Alkanes, Organic]","[Coal, Fossil Fuels]"
2555,2556,সমসংযোজী কার্বন–হাইড্রোজেনের সম্পৃক্ত শ্রেণীটি...,"[Alkenes, Organic]","[Alkanes, Organic]"
2556,2557,দ্বিবন্ধনযুক্ত অসম্পৃক্ত শ্রেণীটির নাম কী?,"[Alkynes, Organic]","[Alkenes, Organic]"
2557,2558,ত্রিবন্ধনযুক্ত অসম্পৃক্ত শ্রেণীটির নাম কী?,"[Refining, Cracking]","[Alkynes, Organic]"
2558,2559,অপরিশোধিত তেলে ভগ্নাংশ ভেঙে ছোট অণু বানানোর প্...,"[LPG, Fuels]","[Refining, Cracking]"
2559,2560,তরল পেট্রোলিয়াম গ্যাসের সংক্ষিপ্ত নাম কী?,"[Gas Safety, Natural Gas]","[LPG, Fuels]"
2560,2561,প্রাকৃতিক গ্যাসে দুর্গন্ধ যুক্ত করতে যে যৌগ যো...,"[Petroleum Fractions, Fuels]","[Gas Safety, Natural Gas]"
2561,2562,"কাঁচ তৈরি ও ধাতু গলাতে ব্যবহৃত, কেরোসিনের ওপরে...","[Organic Reactions, Alkanes]","[Petroleum Fractions, Fuels]"
2562,2563,অ্যালকেন থেকে হ্যালোজেন যোগে যে বিক্রিয়া ঘটে ত...,"[Qualitative Tests, Alkenes]","[Organic Reactions, Alkanes]"
2563,2564,অ্যালকিনের দ্রুত শনাক্তকরণে যে রিএজেন্ট কমলা-ল...,"[Alkanes, Nomenclature]","[Qualitative Tests, Alkenes]"
2564,2565,অ্যালকেনের আরেক নাম (প্রচলিত) কী?,"[LPG, Fractions]","[Alkanes, Nomenclature]"
2565,2566,"অপরিশোধিত তেলের সবচেয়ে হালকা ভগ্নাংশ, গ্যাস রা...","[Gasoline, Transport Fuels]","[LPG, Fractions]"
2566,2567,গ্যাসোলিনের আরেক প্রচলিত নাম কী?,"[Addition Reactions, Catalysis]","[Gasoline, Transport Fuels]"
2567,2568,তাপ না বাড়িয়ে জৈব পদার্থে হাইড্রোজেন জুড়ার প্র...,"[Polymers, Materials]","[Addition Reactions, Catalysis]"
2568,2569,দীর্ঘ শৃঙ্খল মনোমার থেকে বিশাল অণু তৈরির প্রক্...,"[Polyethylene, Monomers]","[Polymers, Materials]"
2569,2570,ইথিন মনোমার থেকে গঠিত প্রচলিত প্লাস্টিকের নাম কী?,"[Natural Gas, Transport]","[Polyethylene, Monomers]"
2570,2571,প্রাকৃতিক গ্যাসকে তরল করে দূরপাল্লায় বহনে যে ন...,"[Fuels, Engines]","[Natural Gas, Transport]"
2571,2572,জ্বালানিতে নকিং কমাতে ব্যবহৃত পরিমাপক সূচকের ন...,"[Bitumen, Fractions]","[Fuels, Engines]"
2572,2573,"অপরিশোধিত তেলের গাঢ়, আঠালো সবচেয়ে ভারী অবশিষ্ট...","[Coalification, Coal]","[Bitumen, Fractions]"
2573,2574,"কয়লা গঠনের প্রাথমিক, পানি-সমৃদ্ধ ও কম কার্বনযু...","[Petroleum Geology, Reservoirs]","[Coalification, Coal]"
2574,2575,ভূগর্ভস্থ শিলার রন্ধ্রে আটকে থাকা তেল/গ্যাসকে ...,"[Upstream Processing, Refining]","[Petroleum Geology, Reservoirs]"
2575,2576,তেল কূপ থেকে উঠে আসা পানি অপসারণসহ প্রাথমিক প্...,"[Laboratory, Solvents]","[Upstream Processing, Refining]"
2576,2577,পেট্রোলিয়াম ইথারের প্রধান ব্যবহার কী—এক/দুই শব...,"[Polymerization, Kinetics]","[Laboratory, Solvents]"
2577,2578,অ্যালকিনে পলিমারাইজেশনের সূচনা করতে ব্যবহৃত পদ...,"[Recycling, Plastics]","[Polymerization, Kinetics]"
2578,2579,প্লাস্টিক পুনঃব্যবহারযোগ্য কিনা বোঝাতে যে প্রত...,"[Gas Processing, Safety]","[Recycling, Plastics]"
2579,2580,প্রাকৃতিক গ্যাসের সালফার অপসারণ প্রক্রিয়ার সাধ...,"[CNG, Transport Fuels]","[Gas Processing, Safety]"
2580,2581,সংকুচিত প্রাকৃতিক গ্যাসের সংক্ষিপ্ত রূপ কী?,"[Kerosene, Fractions]","[CNG, Transport Fuels]"
2581,2582,কাঁচা তেলের যে অংশটি কেরোসিন নামে পরিচিত—এটি ক...,"[Cracking, Refining]","[Kerosene, Fractions]"
2582,2583,রিফাইনারিতে ভারী হাইড্রোকার্বন ভেঙে হালকা তৈরি...,NaN,"[Cracking, Refining]"
2583,2584,তরল জ্বালানি থেকে গ্যাসীয় জ্বালানিতে রূপান্তর...,"[Reforming, Refining]","[Reforming, Refining]"

In [81]:
print(
    "Missing TopicTags after repair:",
    df_clean["TopicTags"].isna().sum()
)

Missing TopicTags after repair: 0

In [82]:
df_clean["TopicTags"].apply(type).value_counts()

TopicTags
<class 'list'>    11257
Name: count, dtype: int64

In [83]:
errors_df["error_type"] = errors_df["error"].str.split(":").str[0]

errors_df["error_type"].value_counts()

error_type
Invalid \escape            27
Expecting ',' delimiter     1
Extra data                  1
Name: count, dtype: int64

In [84]:
errors_df[
    [
        "subject",
        "source_line",
        "error_type",
        "raw_text"
    ]
].head(5)

,subject,source_line,error_type,raw_text
0,Physics,194,"Expecting ',' delimiter","{""Question"":""ডিগ্রি (°), মিনিট (') ও সেকেন্ড (..."
1,Physics,283,Invalid \escape,"{""Question"":""একটি গোলকের আয়তন নির্ণয়ের সূত্র..."
2,Physics,297,Invalid \escape,"{""Question"":""আয়তাকার বস্তুর আয়তন নির্ণয়ের স..."
3,Physics,298,Invalid \escape,"{""Question"":""প্রস্থচ্ছেদের ক্ষেত্রফল নির্ণয়ের..."
4,Physics,476,Invalid \escape,"{""Question"": ""একটি বস্তুর প্রাথমিক বেগ শূন্য হ..."

In [85]:
latex_commands = [
    "times",
    "text",
    "frac",
    "pi",
    "Delta",
    "cdot",
    "epsilon",
    "to",
    "propto",
    "rightarrow",
    "implies",
    "tfrac",
    "approx"
]

In [86]:
import re

In [87]:
latex_pattern = re.compile(
    r'(?<!\\)\\(' + '|'.join(latex_commands) + r')\b'
)

In [88]:
def protect_latex_backslashes(raw_line):

    repaired_line = latex_pattern.sub(
        lambda match: "\\\\" + match.group(1),
        raw_line
    )

    return repaired_line

In [89]:
test_text = r'Formula: $F = \frac{1}{2} \times m$'

print("Before:")
print(test_text)

print("\nAfter protection:")
print(protect_latex_backslashes(test_text))

Before:
Formula: $F = \frac{1}{2} \times m$

After protection:
Formula: $F = \\frac{1}{2} \\times m$

In [90]:
def repair_special_json_errors(raw_line, file_name, line_number):

    # Physics line 194:
    # Escape the double quote used as the seconds symbol
    if (
        file_name == "SSC_Physics_Dataset.jsonl"
        and line_number == 194
    ):
        raw_line = raw_line.replace(
            'সেকেন্ড ("")',
            'সেকেন্ড (\\"")'
        )

    # Biology line 2823:
    # Remove the extra closing brace after Candidates_Answers
    if (
        file_name == "SSC_Biology_Datasets.jsonl"
        and line_number == 2823
    ):
        raw_line = raw_line.replace(
            ']}, "Convergence"',
            '], "Convergence"'
        )

    return raw_line

In [91]:
def repair_raw_json_line(raw_line, file_name, line_number):

    raw_line = protect_latex_backslashes(raw_line)

    raw_line = repair_special_json_errors(
        raw_line,
        file_name,
        line_number
    )

    return raw_line

In [92]:
def load_and_repair_jsonl(file_path, subject):

    valid_records = []
    remaining_errors = []

    with open(file_path, "r", encoding="utf-8") as file:

        for line_number, raw_line in enumerate(file, start=1):

            raw_line = raw_line.strip()

            if not raw_line:
                continue

            repaired_line = repair_raw_json_line(
                raw_line=raw_line,
                file_name=file_path.name,
                line_number=line_number
            )

            try:
                record = json.loads(repaired_line)

                record["subject"] = subject
                record["source_file"] = file_path.name
                record["source_line"] = line_number

                valid_records.append(record)

            except json.JSONDecodeError as error:

                remaining_errors.append({
                    "subject": subject,
                    "source_file": file_path.name,
                    "source_line": line_number,
                    "error": str(error),
                    "raw_text": raw_line,
                    "repaired_text": repaired_line
                })

    return valid_records, remaining_errors

In [93]:
rebuilt_records = []
remaining_errors = []

for file_path in jsonl_files:

    file_name = file_path.name.lower()

    if "biology" in file_name:
        subject = "Biology"

    elif "chemistry" in file_name:
        subject = "Chemistry"

    elif "physics" in file_name:
        subject = "Physics"

    else:
        subject = "Unknown"

    records, errors = load_and_repair_jsonl(
        file_path=file_path,
        subject=subject
    )

    rebuilt_records.extend(records)
    remaining_errors.extend(errors)

In [94]:
df_rebuilt = pd.DataFrame(rebuilt_records)
remaining_errors_df = pd.DataFrame(remaining_errors)

In [95]:
print("Rebuilt records:", len(df_rebuilt))
print("Remaining malformed records:", len(remaining_errors_df))

Rebuilt records: 11277
Remaining malformed records: 9

In [96]:
df_rebuilt["subject"].value_counts()

subject
Biology      4859
Physics      3384
Chemistry    3034
Name: count, dtype: int64

In [97]:
df_rebuilt.loc[
    (df_rebuilt["source_file"] == "SSC_Physics_Dataset.jsonl") &
    (df_rebuilt["source_line"] == 89),
    [
        "Question",
        "Convergence_Ranked"
    ]
]

,Question,Convergence_Ranked
3122,এক অ্যাম্পিয়ারের সংজ্ঞা দাও।,[দুটি সমান্তরাল তারের মধ্যে আকর্ষণ বলের উপর ভি...

In [98]:
df_rebuilt.loc[
    (df_rebuilt["source_file"] == "SSC_Physics_Dataset.jsonl") &
    (df_rebuilt["source_line"] == 145),
    [
        "Question",
        "ExactAnswer"
    ]
]

                                               Question ExactAnswer
3178  $S=ut+\frac{1}{2}at^{2}$ সমীকরণে $ut$ এর মাত্র...           L

In [99]:
def contains_suspicious_control_character(value):

    if isinstance(value, str):
        return any(
            char in value
            for char in ["\t", "\f", "\r"]
        )

    if isinstance(value, list):
        return any(
            contains_suspicious_control_character(item)
            for item in value
        )

    if isinstance(value, dict):
        return any(
            contains_suspicious_control_character(item)
            for item in value.values()
        )

    return False

In [100]:
suspicious_rows = df_rebuilt[
    df_rebuilt.apply(
        lambda row: any(
            contains_suspicious_control_character(value)
            for value in row
        ),
        axis=1
    )
]

print(
    "Rows with suspicious control characters:",
    len(suspicious_rows)
)

Rows with suspicious control characters: 11

In [101]:
print("Rebuilt records:", len(df_rebuilt))
print("Remaining malformed records:", len(remaining_errors_df))

df_rebuilt["subject"].value_counts()

Rebuilt records: 11277
Remaining malformed records: 9

subject
Biology      4859
Physics      3384
Chemistry    3034
Name: count, dtype: int64

In [102]:
latex_pattern = re.compile(
    r'(?<!\\)\\('
    + '|'.join(map(re.escape, latex_commands))
    + r')(?![A-Za-z])'
)

In [103]:
map(re.escape, latex_commands)

In [104]:
def repair_special_json_errors(raw_line, file_name, line_number):

    # Physics line 194:
    # Both double quotes inside the JSON string must be escaped.
    if (
        file_name == "SSC_Physics_Dataset.jsonl"
        and line_number == 194
    ):
        raw_line = raw_line.replace(
            'সেকেন্ড ("")',
            'সেকেন্ড (\\"\\")'
        )

    # Biology line 2823:
    # Remove the extra closing brace.
    if (
        file_name == "SSC_Biology_Datasets.jsonl"
        and line_number == 2823
    ):
        raw_line = raw_line.replace(
            ']}, "Convergence"',
            '], "Convergence"'
        )

    return raw_line

In [105]:
import json
import re
import pandas as pd
from pathlib import Path

In [106]:
latex_commands = [
    "times",
    "text",
    "frac",
    "pi",
    "Delta",
    "cdot",
    "epsilon",
    "to",
    "propto",
    "rightarrow",
    "implies",
    "tfrac",
    "approx"
]

In [107]:
latex_pattern = re.compile(
    r'(?<!\\)\\('
    + '|'.join(map(re.escape, latex_commands))
    + r')(?![A-Za-z])'
)

In [108]:
def protect_latex_backslashes(raw_line):

    repaired_line = latex_pattern.sub(
        lambda match: "\\\\" + match.group(1),
        raw_line
    )

    return repaired_line

In [109]:
def repair_special_json_errors(raw_line, file_name, line_number):

    if (
        file_name == "SSC_Physics_Dataset.jsonl"
        and line_number == 194
    ):
        raw_line = raw_line.replace(
            'সেকেন্ড ("")',
            'সেকেন্ড (\\"\\")'
        )

    if (
        file_name == "SSC_Biology_Datasets.jsonl"
        and line_number == 2823
    ):
        raw_line = raw_line.replace(
            ']}, "Convergence"',
            '], "Convergence"'
        )

    return raw_line

In [110]:
def repair_raw_json_line(raw_line, file_name, line_number):

    raw_line = protect_latex_backslashes(raw_line)

    raw_line = repair_special_json_errors(
        raw_line,
        file_name,
        line_number
    )

    return raw_line

In [111]:
def load_and_repair_jsonl(file_path, subject):

    valid_records = []
    remaining_errors = []

    with open(file_path, "r", encoding="utf-8") as file:

        for line_number, raw_line in enumerate(file, start=1):

            raw_line = raw_line.strip()

            if not raw_line:
                continue

            repaired_line = repair_raw_json_line(
                raw_line=raw_line,
                file_name=file_path.name,
                line_number=line_number
            )

            try:
                record = json.loads(repaired_line)

                record["subject"] = subject
                record["source_file"] = file_path.name
                record["source_line"] = line_number

                valid_records.append(record)

            except json.JSONDecodeError as error:

                remaining_errors.append({
                    "subject": subject,
                    "source_file": file_path.name,
                    "source_line": line_number,
                    "error": str(error),
                    "raw_text": raw_line,
                    "repaired_text": repaired_line
                })

    return valid_records, remaining_errors

In [112]:
rebuilt_records = []
remaining_errors = []

In [113]:
for file_path in jsonl_files:

    file_name = file_path.name.lower()

    if "biology" in file_name:
        subject = "Biology"

    elif "chemistry" in file_name:
        subject = "Chemistry"

    elif "physics" in file_name:
        subject = "Physics"

    else:
        subject = "Unknown"

    records, errors = load_and_repair_jsonl(
        file_path=file_path,
        subject=subject
    )

    rebuilt_records.extend(records)
    remaining_errors.extend(errors)

In [114]:
df_rebuilt = pd.DataFrame(rebuilt_records)

remaining_errors_df = pd.DataFrame(
    remaining_errors
)

In [115]:
print("Rebuilt records:", len(df_rebuilt))
print(
    "Remaining malformed records:",
    len(remaining_errors_df)
)

print()

print(
    df_rebuilt["subject"]
    .value_counts()
)

Rebuilt records: 11286
Remaining malformed records: 0

subject
Biology      4859
Physics      3393
Chemistry    3034
Name: count, dtype: int64

In [116]:
def contains_suspicious_control_character(value):

    if isinstance(value, str):
        return any(
            char in value
            for char in ["\t", "\f", "\r"]
        )

    if isinstance(value, list):
        return any(
            contains_suspicious_control_character(item)
            for item in value
        )

    if isinstance(value, dict):
        return any(
            contains_suspicious_control_character(item)
            for item in value.values()
        )

    return False

In [117]:
suspicious_rows = df_rebuilt[
    df_rebuilt.apply(
        lambda row: any(
            contains_suspicious_control_character(value)
            for value in row
        ),
        axis=1
    )
]

print(
    "Rows with suspicious control characters:",
    len(suspicious_rows)
)

Rows with suspicious control characters: 0

In [118]:
df_raw_repaired = df_rebuilt.copy()

In [119]:
def build_clean_dataframe(df_input):

    df_clean = df_input.copy()

    # -----------------------------------
    # 1. Standardize Question schema
    # -----------------------------------
    if "question" in df_clean.columns:
        df_clean["Question"] = df_clean["Question"].fillna(
            df_clean["question"]
        )

    # -----------------------------------
    # 2. Standardize Hints schema
    # -----------------------------------
    if "hints" in df_clean.columns:
        df_clean["Hints"] = df_clean["Hints"].fillna(
            df_clean["hints"]
        )

    # -----------------------------------
    # 3. Remove duplicate schema columns
    # -----------------------------------
    columns_to_drop = [
        column
        for column in ["question", "hints"]
        if column in df_clean.columns
    ]

    df_clean = df_clean.drop(
        columns=columns_to_drop
    )

    # -----------------------------------
    # 4. Normalize ExactAnswer
    # -----------------------------------
    df_clean["ExactAnswer"] = df_clean["ExactAnswer"].apply(
        lambda value:
            value if isinstance(value, list)
            else [value] if isinstance(value, str)
            else value
    )

    # -----------------------------------
    # 5. Remove empty Sources metadata
    # -----------------------------------
    if "Sources" in df_clean.columns:
        df_clean = df_clean.drop(
            columns=["Sources"]
        )

    # -----------------------------------
    # 6. Preserve original TopicTags
    # -----------------------------------
    df_clean["TopicTags_original"] = df_clean[
        "TopicTags"
    ].apply(
        lambda value:
            value.copy()
            if isinstance(value, list)
            else value
    )

    # -----------------------------------
    # 7. Repair known Chemistry tag shift
    # -----------------------------------
    chemistry_mask = (
        df_clean["source_file"]
        == "SSC_Chemistry_Dataset.jsonl"
    )

    for line_number in range(2555, 2584):

        previous_mask = (
            chemistry_mask
            & (df_clean["source_line"] == line_number - 1)
        )

        current_mask = (
            chemistry_mask
            & (df_clean["source_line"] == line_number)
        )

        previous_tags = df_clean.loc[
            previous_mask,
            "TopicTags_original"
        ].iloc[0]

        current_index = df_clean.index[
            current_mask
        ][0]

        df_clean.at[
            current_index,
            "TopicTags"
        ] = previous_tags.copy()

    # -----------------------------------
    # 8. Impute Chemistry line 2554
    #    using the near-duplicate line 2588
    # -----------------------------------
    target_mask = (
        chemistry_mask
        & (df_clean["source_line"] == 2554)
    )

    reference_mask = (
        chemistry_mask
        & (df_clean["source_line"] == 2588)
    )

    reference_tags = df_clean.loc[
        reference_mask,
        "TopicTags_original"
    ].iloc[0]

    target_index = df_clean.index[
        target_mask
    ][0]

    df_clean.at[
        target_index,
        "TopicTags"
    ] = reference_tags.copy()

    return df_clean

In [120]:
df_clean = build_clean_dataframe(
    df_raw_repaired
)

In [121]:
df_clean = build_clean_dataframe(df_raw_repaired)

In [122]:
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

print(
    "Missing Question:",
    df_clean["Question"].isna().sum()
)

print(
    "Missing Hints:",
    df_clean["Hints"].isna().sum()
)

print(
    "Missing TopicTags:",
    df_clean["TopicTags"].isna().sum()
)

print()
print(
    df_clean["ExactAnswer"]
    .apply(type)
    .value_counts()
)

Rows: 11286
Columns: 11
Missing Question: 0
Missing Hints: 0
Missing TopicTags: 0

ExactAnswer
<class 'list'>    11286
Name: count, dtype: int64

In [123]:
empty_answer_mask = df_clean["ExactAnswer"].apply(
    lambda value:
        isinstance(value, list)
        and len(value) == 0
)

empty_answer_rows = df_clean[
    empty_answer_mask
]

print(
    "Rows with empty ExactAnswer:",
    len(empty_answer_rows)
)

Rows with empty ExactAnswer: 0

In [124]:
empty_answer_rows[
    [
        "Question",
        "ExactAnswer",
        "Candidates_Answers",
        "subject",
        "source_file",
        "source_line"
    ]
]

Empty DataFrame
Columns: [Question, ExactAnswer, Candidates_Answers, subject, source_file, source_line]
Index: []

In [125]:
empty_hint_mask = df_clean["Hints"].apply(
    lambda value:
        isinstance(value, list)
        and len(value) == 0
)

empty_hint_rows = df_clean[
    empty_hint_mask
]

print(
    "Rows with zero hints:",
    len(empty_hint_rows)
)

Rows with zero hints: 1

In [126]:
empty_hint_rows[
    [
        "Question",
        "Hints",
        "ExactAnswer",
        "subject",
        "source_line"
    ]
]

,Question,Hints,ExactAnswer,subject,source_line
1939,দ্রাব্যতা গুণফল (Ksp) কাকে বলে?,[],[কম দ্রবণীয় লবণের সমতার আয়ন গুণফল।],Chemistry,1940

In [127]:
df_clean["hint_count"] = df_clean["Hints"].apply(
    lambda value:
        len(value)
        if isinstance(value, list)
        else None
)

In [128]:
df_clean["hint_count"].value_counts().sort_index()

hint_count
0        1
2        1
3       25
4       24
5    10612
6      367
7      254
8        2
Name: count, dtype: int64

In [129]:
empty_candidate_mask = df_clean[
    "Candidates_Answers"
].apply(
    lambda value:
        isinstance(value, list)
        and len(value) == 0
)

empty_candidate_rows = df_clean[
    empty_candidate_mask
]

print(
    "Rows with empty Candidates_Answers:",
    len(empty_candidate_rows)
)

Rows with empty Candidates_Answers: 0

In [130]:
duplicate_question_mask = df_clean.duplicated(
    subset=["Question"],
    keep=False
)

duplicate_question_rows = df_clean[
    duplicate_question_mask
]

print(
    "Rows involved in duplicate questions:",
    len(duplicate_question_rows)
)

Rows involved in duplicate questions: 679

In [131]:
core_columns = [
    "Question",
    "Hints",
    "ExactAnswer",
    "Candidates_Answers",
    "Convergence",
    "Convergence_Ranked",
    "TopicTags"
]

In [132]:
def create_record_signature(row):

    core_data = {
        column: row[column]
        for column in core_columns
    }

    return json.dumps(
        core_data,
        ensure_ascii=False,
        sort_keys=True
    )

In [133]:
df_clean["record_signature"] = df_clean.apply(
    create_record_signature,
    axis=1
)

In [134]:
exact_duplicate_mask = df_clean[
    "record_signature"
].duplicated(
    keep=False
)

exact_duplicate_rows = df_clean[
    exact_duplicate_mask
]

print(
    "Rows involved in exact core duplicates:",
    len(exact_duplicate_rows)
)

Rows involved in exact core duplicates: 36

In [135]:
ensure_ascii=False

In [136]:
df_clean["has_zero_hints"] = (
    df_clean["hint_count"] == 0
)

df_clean["has_fewer_than_5_hints"] = (
    df_clean["hint_count"] < 5
)

df_clean["has_more_than_5_hints"] = (
    df_clean["hint_count"] > 5
)

In [137]:
df_clean[
    [
        "has_zero_hints",
        "has_fewer_than_5_hints",
        "has_more_than_5_hints"
    ]
].sum()

has_zero_hints              1
has_fewer_than_5_hints     51
has_more_than_5_hints     623
dtype: int64

In [138]:
exact_duplicate_groups = (
    df_clean[
        df_clean["record_signature"].duplicated(
            keep=False
        )
    ]
    .sort_values(
        ["record_signature", "subject", "source_line"]
    )
)

In [139]:
exact_duplicate_groups[
    [
        "Question",
        "ExactAnswer",
        "subject",
        "source_line"
    ]
]

,Question,ExactAnswer,subject,source_line
9187,উপাঙ্গীয় কঙ্কাল কোন ধরণের গঠন তৈরি করে?,[অঙ্গসংস্থানিক গঠন],Biology,2761
9206,উপাঙ্গীয় কঙ্কাল কোন ধরণের গঠন তৈরি করে?,[অঙ্গসংস্থানিক গঠন],Biology,2780
9186,অক্ষীয় কঙ্কাল কোন ধরণের গঠন তৈরি করে?,[কেন্দ্রীয় গঠন],Biology,2760
9205,অক্ষীয় কঙ্কাল কোন ধরণের গঠন তৈরি করে?,[কেন্দ্রীয় গঠন],Biology,2779
9183,মধ্যকর্ণের অস্থি কোন ধরণের অস্থি?,[ছোট অস্থি],Biology,2757
9202,মধ্যকর্ণের অস্থি কোন ধরণের অস্থি?,[ছোট অস্থি],Biology,2776
9196,থোরাসিক কশেরুকার সংখ্যা কতটি?,[১২],Biology,2770
9215,থোরাসিক কশেরুকার সংখ্যা কতটি?,[১২],Biology,2789
9185,উপাঙ্গীয় কঙ্কাল কয়টি হাড় নিয়ে গঠিত?,[১২৬],Biology,2759
9204,উপাঙ্গীয় কঙ্কাল কয়টি হাড় নিয়ে গঠিত?,[১২৬],Biology,2778
9191,সত্য পাঁজরের সংখ্যা কতটি?,[১৪],Biology,2765
9210,সত্য পাঁজরের সংখ্যা কতটি?,[১৪],Biology,2784
9189,মুখমণ্ডলীয় হাড় কয়টি?,[১৪],Biology,2763
9208,মুখমণ্ডলীয় হাড় কয়টি?,[১৪],Biology,2782
9201,শ্রোণি বলয়ে কয়টি হাড় থাকে?,[২ জোড়া (৪)],Biology,2775
9220,শ্রোণি বলয়ে কয়টি হাড় থাকে?,[২ জোড়া (৪)],Biology,2794
9194,মেরুদণ্ড কয়টি কশেরুকা দ্বারা গঠিত?,[৩৩],Biology,2768
9213,মেরুদণ্ড কয়টি কশেরুকা দ্বারা গঠিত?,[৩৩],Biology,2787
9199,কক্সিজিয়াল কশেরুকার সংখ্যা কতটি?,[৪],Biology,2773
9218,কক্সিজিয়াল কশেরুকার সংখ্যা কতটি?,[৪],Biology,2792
9200,কাঁধের বলয়ে কয়টি হাড় থাকে?,[৪],Biology,2774
9219,কাঁধের বলয়ে কয়টি হাড় থাকে?,[৪],Biology,2793
9193,ভাসমান পাঁজরের সংখ্যা কতটি?,[৪],Biology,2767
9212,ভাসমান পাঁজরের সংখ্যা কতটি?,[৪],Biology,2786
9198,স্যাক্রাল কশেরুকার সংখ্যা কতটি?,[৫],Biology,2772
9217,স্যাক্রাল কশেরুকার সংখ্যা কতটি?,[৫],Biology,2791
9197,লাম্বার কশেরুকার সংখ্যা কতটি?,[৫],Biology,2771
9216,লাম্বার কশেরুকার সংখ্যা কতটি?,[৫],Biology,2790
9192,মিথ্যা পাঁজরের সংখ্যা কতটি?,[৬],Biology,2766
9211,মিথ্যা পাঁজরের সংখ্যা কতটি?,[৬],Biology,2785
9195,সার্ভাইক্যাল কশেরুকার সংখ্যা কতটি?,[৭],Biology,2769
9214,সার্ভাইক্যাল কশেরুকার সংখ্যা কতটি?,[৭],Biology,2788
9188,করোটিতে কয়টি হাড় থাকে?,[৮],Biology,2762
9207,করোটিতে কয়টি হাড় থাকে?,[৮],Biology,2781
9184,অক্ষীয় কঙ্কাল কয়টি হাড় নিয়ে গঠিত?,[৮০],Biology,2758
9203,অক্ষীয় কঙ্কাল কয়টি হাড় নিয়ে গঠিত?,[৮০],Biology,2777

In [140]:
print(
    "Exact duplicate groups:",
    exact_duplicate_groups[
        "record_signature"
    ].nunique()
)

Exact duplicate groups: 18

In [141]:
df_model = df_clean.drop_duplicates(
    subset=["record_signature"],
    keep="first"
).copy()

In [142]:
print(
    "Clean master records:",
    len(df_clean)
)

print(
    "Model records after exact deduplication:",
    len(df_model)
)

print(
    "Exact copies removed:",
    len(df_clean) - len(df_model)
)

Clean master records: 11286
Model records after exact deduplication: 11268
Exact copies removed: 18

In [143]:
question_group_sizes = (
    df_clean
    .groupby("Question")
    .size()
    .reset_index(name="question_occurrences")
)

In [144]:
duplicate_question_summary = (
    question_group_sizes[
        question_group_sizes["question_occurrences"] > 1
    ]
    .sort_values(
        "question_occurrences",
        ascending=False
    )
)

In [145]:
print(
    "Unique duplicated questions:",
    len(duplicate_question_summary)
)

duplicate_question_summary.head(20)

Unique duplicated questions: 318

                                                Question  question_occurrences
4054                                     ক্ষমতার একক কী?                     4
7378                                বরফ পানিতে ভাসে কেন?                     4
3793    কোনো বস্তুর বেগ অর্ধেক করলে গতিশক্তি কত অংশ হবে?                     3
10290    সূর্য থেকে পৃথিবীতে শক্তি আসে কোন প্রক্রিয়ায়?                     3
3806   কোনো যন্ত্রে প্রদত্ত শক্তি ১০০ জুল এবং লভ্য কা...                     3
2302   একটি বস্তুর ভর দ্বিগুণ এবং বেগ অর্ধেক করলে গতি...                     3
2301   একটি বস্তুর ভর ও বিভব শক্তি দেওয়া থাকলে তার উ...                     3
2300   একটি বস্তুর ভর ও গতিশক্তি দেওয়া থাকলে তার বেগ...                     3
3809   কোনো যন্ত্রের কর্মদক্ষতা ৮০% হলে শক্তির অপচয় ...                     3
2295   একটি বস্তুর উপর একাধিক বল ক্রিয়া করলে মোট কাজ...                     3
2293   একটি বস্তুকে স্থির অবস্থা থেকে গতিশীল করতে যে ...                     3
2292   একটি বস্তুকে মসৃণ তলে ঠেলে নিয়ে যেতে কম কাজ হ...                     3
2636   কঠিন থেকে তরলে রূপান্তরের সময় অণুর দূরত্ব কীভ...                     3
1964                   উত্তল দর্পণের প্রতিচ্ছবি কেমন হয়?                     3
2289   একটি বস্তুকে খাড়া উপরের দিকে নিক্ষেপ করলে সর্...                     3
4296   গাছের পাতায় খাদ্য তৈরির সময় কোন শক্তি কোন শক...                     3
2288   একটি বস্তুকে উপরের দিকে নিক্ষেপ করলে তার গতিশক...                     3
2069   উপর থেকে নিচে পড়ার সময় বস্তুর বিভব শক্তি ক্র...                     3
9316   শক্তির নিত্যতা সূত্র কোন ধরনের সিস্টেমের জন্য ...                     3
2105               ঋণাত্মক কাজের একটি বাস্তব উদাহরণ দাও।                     3

In [146]:
def answer_signature(answer):

    return json.dumps(
        answer,
        ensure_ascii=False,
        sort_keys=True
    )

In [147]:
df_clean["answer_signature"] = (
    df_clean["ExactAnswer"]
    .apply(answer_signature)
)

In [148]:
answer_variants_per_question = (
    df_clean
    .groupby("Question")["answer_signature"]
    .nunique()
)

In [149]:
answer_conflict_questions = (
    answer_variants_per_question[
        answer_variants_per_question > 1
    ]
)

print(
    "Duplicate questions with multiple answer versions:",
    len(answer_conflict_questions)
)

Duplicate questions with multiple answer versions: 114

In [150]:
questions_to_review = (
    answer_conflict_questions
    .index[:10]
)

In [151]:
df_clean[
    df_clean["Question"].isin(
        questions_to_review
    )
][
    [
        "Question",
        "ExactAnswer",
        "Hints",
        "subject",
        "source_line"
    ]
].sort_values(
    ["Question", "source_line"]
)

,Question,ExactAnswer,Hints,subject,source_line
1124,BCl₃ যৌগে অষ্টক অপূর্ণতা দেখা যায় কেন?,[কেন্দ্রীয় পরমাণুর সর্ববহিঃস্থ স্তরে ইলেকট্রন...,[অষ্টক নিয়ম অনুযায়ী স্থিতিশীলতার জন্য শেষ কক...,Chemistry,1125
1174,BCl₃ যৌগে অষ্টক অপূর্ণতা দেখা যায় কেন?,[কেন্দ্রীয় পরমাণু বোরনের সর্ববহিঃস্থ স্তরে ৬ট...,[অষ্টক নিয়মে স্থিতিশীলতার জন্য ৮ ইলেকট্রন ধরা...,Chemistry,1175
651,অক্টেট নীতি কী?,[ভ্যালেন্স শেলে ৮ ইলেকট্রন পূর্ণ হলে স্থিতিশীল...,"[বাহ্যস্তরে আট হলে স্থায়িত্ব, আয়ন/সমযোজী—উভয়...",Chemistry,652
1821,অক্টেট নীতি কী?,[ভ্যালেন্স শেলে ৮ ইলেকট্রন পূর্ণ হলে স্থায়িত্ব...,"[নিষ্ক্রিয় গ্যাসের স্থিতিস্থাপকতা অনুকরণ।, বাহ...",Chemistry,1822
7781,অতিরিক্ত ফাস্ট ফুড খেলে কোন সমস্যাটি হওয়ার সম...,[স্থূলতা],"[খুব উচ্চ ক্যালরি ও কম পুষ্টিগুণের খাবার।, বার...",Biology,1355
9448,অতিরিক্ত ফাস্ট ফুড খেলে কোন সমস্যাটি হওয়ার সম...,[হৃদরোগ],"[এটি হৃদযন্ত্রের সমস্যার সঙ্গে সম্পর্কিত।, এটি...",Biology,3022
3430,অভিকর্ষজ ত্বরণের একক কী?,[অভিকর্ষজ ত্বরণের এসআই একক হলো মিটার/সেকেন্ড² ।],"[এটি ত্বরণের একক।, এর লবে দূরত্বের একক এবং হরে...",Physics,397
3626,অভিকর্ষজ ত্বরণের একক কী?,[অভিকর্ষজ ত্বরণের এসআই একক হলো মিটার প্রতি সেক...,"[এটি একটি ত্বরণ, ত্বরণের একক এবং এর একক একই, এ...",Physics,593
4131,আবহাওয়া পূর্বাভাসে চাপ কেন গুরুত্বপূর্ণ?,[কারণ চাপক্ষেত্রের],"[নিম্নচাপ-ঘূর্ণিঝড়ের উৎস., উচ্চচাপ-শুষ্ক ও স্...",Physics,1098
4231,আবহাওয়া পূর্বাভাসে চাপ কেন গুরুত্বপূর্ণ?,[কারণ উচ্চ/নিম্নচাপের],"[উচ্চচাপ সাধারণত স্থিতিশীল আবহাওয়া আনে, নিম্ন...",Physics,1198
1723,ইলেক্ট্রোপ্লেটিং কী?,[তড়িৎ বিশ্লেষণে ধাতুর উপর অন্য ধাতুর পাতলা আস্...,"[সৌন্দর্য ও ক্ষয়রোধ—দু’ই লক্ষ্য।, ইলেক্ট্রোলাই...",Chemistry,1724
2363,ইলেক্ট্রোপ্লেটিং কী?,[তড়িৎ বিশ্লেষণ প্রক্রিয়ায় একটি ধাতুর উপর অন...,"[এটি ধাতুর ক্ষয় রোধের একটি উপায়।, এতে একটি ধ...",Chemistry,2364
4122,উচ্চতা বাড়লে বায়ুমণ্ডলীয় চাপ কীভাবে পরিবর্ত...,[উচ্চতা বাড়লে],"[বায়ুস্তর উপরে উঠলে পাতলা হয়., উপরের বায়ুস্...",Physics,1089
4222,উচ্চতা বাড়লে বায়ুমণ্ডলীয় চাপ কীভাবে পরিবর্ত...,[উচ্চতা বাড়ার],"[উচ্চতায় বায়ু পাতলা হয়ে যায়, বায়ুস্তম্ভের...",Physics,1189
4132,উচ্চতায় উঠলে রান্নার সময় পানি কেন দ্রুত বাষ্...,[উচ্চতায় চাপ],"[উচ্চতায় বায়ুচাপ কম., স্ফুটনাঙ্ক কমে যায়., ...",Physics,1099
4232,উচ্চতায় উঠলে রান্নার সময় পানি কেন দ্রুত বাষ্...,[চাপ কমে],"[উচ্চতায় চাপ কম, কম চাপ মানে স্ফুটনাঙ্ক কম, ক...",Physics,1199
4703,উত্তল দর্পণের প্রতিচ্ছবি কেমন হয়?,"[সর্বদা ক্ষুদ্র, সোজা, কাল্পনিক।]","[সবসময় সোজা হয়।, সবসময় ভার্চুয়াল হয়।, সবস...",Physics,1670
4719,উত্তল দর্পণের প্রতিচ্ছবি কেমন হয়?,"[সবসময় ক্ষুদ্র, সোজা, কাল্পনিক।]","[Convex মিরর।, সবসময় ভার্চুয়াল।, সবসময় সোজা।, ...",Physics,1686
4883,উত্তল দর্পণের প্রতিচ্ছবি কেমন হয়?,[সবসময় সোজা।],"[দৃশ্যক্ষেত্র বড় করা লক্ষ্য।, স্ক্রিনে ধরা যায়...",Physics,1850
10037,উদ্ভিদে যৌন প্রজননের জন্য পরাগনালী কেন অপরিহার্য?,[ডিম্বাধারে পুরুষ গ্যামেট পৌঁছে নিষেক ঘটাতে পর...,"[বন্ধ গর্ভমুণ্ডে সরাসরি মিলন সম্ভব নয়।, দূরত্...",Biology,3611
10057,উদ্ভিদে যৌন প্রজননের জন্য পরাগনালী কেন অপরিহার্য?,[অচল স্পার্মকে ডিম্বাধারে পৌঁছে নিষেক ঘটাতে পর...,"[ফুলের স্ত্রী কোষ গভীরে সুরক্ষিত থাকে।, পুরুষ ...",Biology,3631

In [152]:
output_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"

df_clean.to_json(
    output_path,
    orient="records",
    lines=True,
    force_ascii=False
)

print("Dataset saved successfully!")
print("Saved at:", output_path)
print("Total records:", len(df_clean))

Dataset saved successfully!
Saved at: /kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl
Total records: 11286

In [153]:
import os

print("File exists:", os.path.exists(output_path))
print(
    "File size (MB):",
    round(os.path.getsize(output_path) / (1024 * 1024), 2)
)

File exists: True
File size (MB): 37.19

In [154]:
df_test = pd.read_json(
    output_path,
    lines=True
)

print("Reloaded records:", len(df_test))
print("Reloaded columns:", len(df_test.columns))

Reloaded records: 11286
Reloaded columns: 17

In [155]:
print(type(df_test.loc[0, "Hints"]))
print(type(df_test.loc[0, "ExactAnswer"]))
print(type(df_test.loc[0, "TopicTags"]))

<class 'list'>
<class 'list'>
<class 'list'>

In [156]:
import os

print(os.listdir("/kaggle/working"))

['ssc_banglatutor_preprocessed_stage1.jsonl', '.virtual_documents']

In [157]:
output_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"

print("Exists:", os.path.exists(output_path))
print("Size:", os.path.getsize(output_path), "bytes")

Exists: True
Size: 38998858 bytes

In [158]:
import zipfile

jsonl_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"
zip_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip"

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
    zip_file.write(
        jsonl_path,
        arcname="ssc_banglatutor_preprocessed_stage1.jsonl"
    )

print("ZIP created successfully!")
print(zip_path)

ZIP created successfully!
/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip

In [159]:
for file_name in os.listdir("/kaggle/working"):
    file_path = os.path.join("/kaggle/working", file_name)

    if os.path.isfile(file_path):
        size_mb = os.path.getsize(file_path) / (1024 * 1024)
        print(f"{file_name} -> {size_mb:.2f} MB")

ssc_banglatutor_preprocessed_stage1.jsonl -> 37.19 MB
ssc_banglatutor_preprocessed_stage1.zip -> 2.98 MB

In [160]:
import shutil

jsonl_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"

zip_base_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1"

shutil.make_archive(
    zip_base_path,
    "zip",
    root_dir="/kaggle/working",
    base_dir="ssc_banglatutor_preprocessed_stage1.jsonl"
)

print("ZIP created!")
print(zip_base_path + ".zip")

ZIP created!
/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip

In [161]:
import os

print(
    os.path.exists(
        "/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip"
    )
)

True

In [162]:
from IPython.display import FileLink, display

display(
    FileLink(
        "/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip"
    )
)

/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip

In [163]:
import os

zip_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip"
jsonl_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"

print("JSONL exists:", os.path.exists(jsonl_path))
print("ZIP exists:", os.path.exists(zip_path))

if os.path.exists(jsonl_path):
    print(
        "JSONL size:",
        round(os.path.getsize(jsonl_path) / (1024 * 1024), 2),
        "MB"
    )

if os.path.exists(zip_path):
    print(
        "ZIP size:",
        round(os.path.getsize(zip_path) / (1024 * 1024), 2),
        "MB"
    )

JSONL exists: True
ZIP exists: True
JSONL size: 37.19 MB
ZIP size: 2.98 MB

In [164]:
from IPython.display import FileLink, display

display(FileLink(zip_path))

/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip

In [165]:
from IPython.display import FileLink, display

zip_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip"

display(FileLink(zip_path))

/kaggle/working/ssc_banglatutor_preprocessed_stage1.zip

In [166]:
from pathlib import Path

for file in Path("/kaggle/input").rglob("*.jsonl"):
    print(file)

/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/chem/SSC_Chemistry_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/phy/SSC_Physics_Dataset.jsonl
/kaggle/input/datasets/fihabefti/hint-based-dataset3-0/Bio/SSC_Biology_Datasets.jsonl

In [167]:
import pandas as pd

file_path = "/kaggle/working/ssc_banglatutor_preprocessed_stage1.jsonl"

df = pd.read_json(
    file_path,
    lines=True
)

print(df.shape)
df.head()

(11286, 17)

,Question,Hints,ExactAnswer,Candidates_Answers,Convergence,Convergence_Ranked,TopicTags,subject,source_file,source_line,TopicTags_original,hint_count,record_signature,has_zero_hints,has_fewer_than_5_hints,has_more_than_5_hints,answer_signature
0,রসায়ন কী?,"[এটি বিজ্ঞানের একটি শাখা।, পদার্থের গঠন একটি আ...","[বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদ...","[বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং পদ...","[{'Up to 1': 0.5, 'Up to 2': 0.65, 'Up to 3': ...","[এটি বিজ্ঞানের একটি শাখা।, পদার্থের গঠন একটি আ...","[Chemistry, Definition of Chemistry]",Chemistry,SSC_Chemistry_Dataset.jsonl,1,"[Chemistry, Definition of Chemistry]",5,"{""Candidates_Answers"": [""বিজ্ঞানের যে শাখায় প...",False,False,False,"[""বিজ্ঞানের যে শাখায় পদার্থের গঠন, ধর্ম এবং প..."
1,রসায়নের জনক কে?,"[তিনি মধ্যযুগের একজন প্রভাবশালী আল-কেমিস্ট।, ত...",[জাবির ইবনে হাইয়ান],"[জাবির ইবনে হাইয়ান, অ্যান্টনি ল্যাভয়সিয়ে, র...","{'Up to 1': 0.6000000000000001, 'Up to 2': 0.8...","[তিনি মধ্যযুগের একজন প্রভাবশালী আল-কেমিস্ট।, ত...",[History of Chemistry],Chemistry,SSC_Chemistry_Dataset.jsonl,2,[History of Chemistry],5,"{""Candidates_Answers"": [""জাবির ইবনে হাইয়ান"", ...",False,False,False,"[""জাবির ইবনে হাইয়ান""]"
2,আধুনিক রসায়নের জনক কে?,[তিনি ছিলেন অষ্টাদশ শতাব্দীর একজন ফরাসি অভিজাত...,[অ্যান্টনি ল্যাভয়সিয়ে],"[অ্যান্টনি ল্যাভয়সিয়ে, জাবির ইবনে হাইয়ান, স...","{'Up to 1': 0.6000000000000001, 'Up to 2': 0.8...",[তিনি ছিলেন অষ্টাদশ শতাব্দীর একজন ফরাসি অভিজাত...,[History of Chemistry],Chemistry,SSC_Chemistry_Dataset.jsonl,3,[History of Chemistry],5,"{""Candidates_Answers"": [""অ্যান্টনি ল্যাভয়সিয়...",False,False,False,"[""অ্যান্টনি ল্যাভয়সিয়ে""]"
3,রসায়নের গবেষণার দ্বিতীয় ধাপ কোনটি?,"[এটি বৈজ্ঞানিক পদ্ধতির একটি ক্রমিক পদক্ষেপ।, এ...",[পর্যবেক্ষণ ও তথ্য সংগ্রহ],"[পর্যবেক্ষণ ও তথ্য সংগ্রহ, সমস্যা শনাক্তকরণ, ফ...","{'Up to 1': 0.65, 'Up to 2': 0.8, 'Up to 3': 0...","[এটি বৈজ্ঞানিক পদ্ধতির একটি ক্রমিক পদক্ষেপ।, এ...",[Chemistry Research Process],Chemistry,SSC_Chemistry_Dataset.jsonl,4,[Chemistry Research Process],5,"{""Candidates_Answers"": [""পর্যবেক্ষণ ও তথ্য সংগ...",False,False,False,"[""পর্যবেক্ষণ ও তথ্য সংগ্রহ""]"
4,কোনটি 'বিষাক্ত' রাসায়নিক পদার্থের সাংকেতিক চি...,[এই চিহ্নটি নির্দেশ করে যে পদার্থটি মানবদেহ বা...,[একটি খুলি ও দুটি হাড়ের চিহ্ন],"[একটি খুলি ও দুটি হাড়ের চিহ্ন, আগুন ও শিখার চ...","{'Up to 1': 0.8, 'Up to 2': 0.9500000000000001...",[এই চিহ্নটি নির্দেশ করে যে পদার্থটি মানবদেহ বা...,[Chemical Hazard Symbols],Chemistry,SSC_Chemistry_Dataset.jsonl,5,[Chemical Hazard Symbols],5,"{""Candidates_Answers"": [""একটি খুলি ও দুটি হাড়...",False,False,False,"[""একটি খুলি ও দুটি হাড়ের চিহ্ন""]"